INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (1 , 30 , 1 , 463 , '2013-01-29' , 1 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (2 , 57 , 1 , 195 , '2013-01-12' , 1 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (3 , 85 , 1 , 461 , '2013-01-15' , 0 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (4 , 163 , 2 , 212 , '2013-01-21' , 2 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (5 , 167 , 2 , 338 , '2013-01-06' , 0 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (6 , 77 , 3 , 25 , '2013-01-14' , 0 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (7 , 249 , 3 , 232 , '2013-01-26' , 2 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (8 , 141 , 4 , 178 , '2013-01-24' , 1 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (9 , 123 , 4 , 86 , '2013-01-13' , 4 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (10 , 57 , 5 , 74 , '2013-01-30' , 0 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (11 , 121 , 5 , 79 , '2013-01-26' , 0 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (12 , 110 , 6 , 217 , '2013-02-15' , 1 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (13 , 124 , 6 , 46 , '2013-02-05' , 1 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (14 , 30 , 7 , 39 , '2013-03-01' , 0 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (15 , 113 , 7 , 409 , '2013-02-17' , 0 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (16 , 84 , 8 , 36 , '2013-02-28' , 1 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (17 , 56 , 8 , 361 , '2013-02-10' , 0 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (18 , 194 , 8 , 73 , '2013-02-07' , 3 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (19 , 54 , 9 , 451 , '2013-03-06' , 1 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (20 , 26 , 9 , 365 , '2013-03-09' , 0 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (21 , 11 , 9 , 56 , '2013-03-14' , 0 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (22 , 101 , 9 , 195 , '2013-02-26' , 1 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (23 , 148 , 10 , 297 , '2013-03-13' , 1 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (24 , 159 , 11 , 453 , '2013-03-19' , 1 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (25 , 149 , 11 , 308 , '2013-03-06' , 1 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (26 , 45 , 12 , 162 , '2013-03-07' , 0 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (27 , 19 , 12 , 337 , '2013-03-11' , 0 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (28 , 87 , 12 , 435 , '2013-03-05' , 2 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (29 , 145 , 13 , 422 , '2013-04-01' , 1 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (30 , 247 , 14 , 255 , '2013-03-07' , 1 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (31 , 96 , 15 , 135 , '2013-03-08' , 1 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (32 , 153 , 15 , 246 , '2013-03-26' , 0 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (33 , 44 , 16 , 55 , '2013-04-10' , 1 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (34 , 54 , 16 , 99 , '2013-04-21' , 1 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (35 , 65 , 16 , 442 , '2013-04-03' , 1 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (36 , 7 , 17 , 209 , '2013-04-09' , 0 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (37 , 73 , 17 , 39 , '2013-04-09' , 1 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (38 , 49 , 17 , 29 , '2013-04-26' , 0 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (39 , 63 , 17 , 99 , '2013-04-06' , 0 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (40 , 33 , 18 , 278 , '2013-04-07' , 0 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (41 , 146 , 18 , 276 , '2013-03-31' , 2 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (42 , 60 , 19 , 169 , '2013-04-10' , 1 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (43 , 8 , 19 , 398 , '2013-04-29' , 0 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (44 , 101 , 19 , 8 , '2013-04-15' , 0 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (45 , 157 , 20 , 333 , '2013-04-23' , 3 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (46 , 65 , 20 , 358 , '2013-05-15' , 0 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (47 , 7 , 21 , 119 , '2013-04-24' , 0 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (48 , 72 , 21 , 30 , '2013-05-21' , 1 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (49 , 122 , 21 , 406 , '2013-04-23' , 1 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (50 , 67 , 22 , 250 , '2013-05-23' , 2 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (51 , 114 , 22 , 188 , '2013-05-10' , 0 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (52 , 37 , 22 , 152 , '2013-05-11' , 0 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (53 , 82 , 22 , 378 , '2013-05-08' , 1 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (54 , 94 , 23 , 284 , '2013-05-30' , 1 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (55 , 20 , 23 , 123 , '2013-05-24' , 0 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (56 , 16 , 23 , 287 , '2013-05-27' , 0 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (57 , 114 , 23 , 69 , '2013-06-10' , 1 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (58 , 2 , 24 , 161 , '2013-05-29' , 0 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (59 , 50 , 24 , 445 , '2013-06-14' , 0 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (60 , 140 , 24 , 245 , '2013-06-09' , 1 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (61 , 205 , 25 , 219 , '2013-05-28' , 0 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (62 , 242 , 25 , 284 , '2013-05-26' , 4 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (63 , 116 , 26 , 34 , '2013-05-25' , 1 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (64 , 29 , 27 , 181 , '2013-05-24' , 0 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (65 , 19 , 27 , 302 , '2013-06-08' , 1 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (66 , 39 , 27 , 130 , '2013-06-21' , 0 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (67 , 130 , 27 , 452 , '2013-05-30' , 1 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (68 , 5 , 28 , 241 , '2013-05-26' , 0 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (69 , 53 , 28 , 367 , '2013-06-06' , 0 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (70 , 20 , 28 , 183 , '2013-05-27' , 0 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (71 , 88 , 28 , 28 , '2013-05-28' , 1 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (72 , 92 , 29 , 270 , '2013-06-06' , 2 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (73 , 60 , 29 , 368 , '2013-06-04' , 1 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (74 , 107 , 30 , 2 , '2013-06-03' , 3 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (75 , 13 , 30 , 321 , '2013-06-29' , 0 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (76 , 123 , 31 , 100 , '2013-06-18' , 3 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (77 , 116 , 31 , 15 , '2013-06-15' , 2 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (78 , 11 , 32 , 195 , '2013-06-10' , 0 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (79 , 40 , 32 , 107 , '2013-07-02' , 0 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (80 , 223 , 32 , 149 , '2013-06-08' , 0 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (81 , 2 , 33 , 342 , '2013-06-27' , 0 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (82 , 127 , 33 , 398 , '2013-06-24' , 1 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (83 , 190 , 33 , 99 , '2013-06-28' , 4 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (84 , 32 , 34 , 38 , '2013-07-03' , 0 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (85 , 45 , 34 , 353 , '2013-06-29' , 0 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (86 , 17 , 34 , 323 , '2013-07-02' , 0 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (87 , 84 , 34 , 242 , '2013-07-08' , 1 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (88 , 136 , 35 , 85 , '2013-06-28' , 2 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (89 , 146 , 35 , 427 , '2013-06-25' , 1 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (90 , 9 , 36 , 3 , '2013-07-30' , 0 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (91 , 82 , 36 , 306 , '2013-07-08' , 1 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (92 , 61 , 36 , 59 , '2013-07-18' , 0 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (93 , 60 , 37 , 386 , '2013-07-10' , 1 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (94 , 93 , 37 , 407 , '2013-07-31' , 0 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (95 , 146 , 38 , 170 , '2013-08-02' , 1 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (96 , 123 , 39 , 465 , '2013-07-24' , 1 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (97 , 195 , 39 , 182 , '2013-08-07' , 0 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (98 , 172 , 40 , 83 , '2013-07-21' , 3 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (99 , 129 , 40 , 109 , '2013-08-08' , 1 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (100 , 6 , 41 , 368 , '2013-07-21' , 0 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (101 , 66 , 41 , 347 , '2013-08-18' , 1 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (102 , 9 , 41 , 147 , '2013-08-03' , 0 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (103 , 21 , 41 , 273 , '2013-07-19' , 0 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (104 , 11 , 41 , 253 , '2013-08-04' , 0 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (105 , 97 , 42 , 136 , '2013-08-21' , 0 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (106 , 73 , 42 , 23 , '2013-09-05' , 0 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (107 , 148 , 43 , 438 , '2013-08-19' , 3 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (108 , 14 , 44 , 23 , '2013-08-23' , 0 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (109 , 27 , 44 , 325 , '2013-08-28' , 0 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (110 , 176 , 44 , 322 , '2013-08-21' , 1 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (111 , 53 , 45 , 299 , '2013-09-14' , 0 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (112 , 33 , 45 , 447 , '2013-08-27' , 0 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (113 , 117 , 45 , 141 , '2013-09-12' , 2 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (114 , 66 , 46 , 68 , '2013-09-15' , 0 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (115 , 5 , 46 , 114 , '2013-09-15' , 0 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (116 , 17 , 46 , 236 , '2013-08-23' , 0 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (117 , 84 , 46 , 343 , '2013-09-19' , 0 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (118 , 76 , 47 , 260 , '2013-09-13' , 1 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (119 , 73 , 47 , 43 , '2013-10-14' , 1 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (120 , 198 , 47 , 243 , '2013-10-07' , 2 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (121 , 101 , 48 , 185 , '2013-10-06' , 1 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (122 , 63 , 48 , 341 , '2013-10-04' , 0 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (123 , 54 , 49 , 470 , '2013-10-08' , 2 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (124 , 74 , 49 , 471 , '2013-10-14' , 0 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (125 , 65 , 49 , 427 , '2013-10-13' , 0 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (126 , 125 , 49 , 9 , '2013-10-10' , 1 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (127 , 74 , 50 , 266 , '2013-10-19' , 0 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (128 , 189 , 50 , 126 , '2013-10-25' , 1 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (129 , 1 , 51 , 376 , '2013-10-02' , 0 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (130 , 197 , 51 , 293 , '2013-10-04' , 2 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (131 , 147 , 52 , 135 , '2013-10-01' , 1 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (132 , 51 , 52 , 190 , '2013-10-20' , 0 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (133 , 226 , 53 , 324 , '2013-10-28' , 1 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (134 , 3 , 53 , 54 , '2013-10-15' , 0 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (135 , 182 , 53 , 89 , '2013-10-25' , 4 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (136 , 83 , 54 , 6 , '2013-10-17' , 1 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (137 , 62 , 54 , 120 , '2013-11-02' , 1 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (138 , 134 , 54 , 194 , '2013-11-03' , 2 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (139 , 125 , 55 , 157 , '2013-11-13' , 2 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (140 , 86 , 55 , 322 , '2013-10-14' , 1 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (141 , 19 , 55 , 431 , '2013-11-04' , 0 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (142 , 206 , 55 , 429 , '2013-11-07' , 2 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (143 , 42 , 56 , 111 , '2013-10-20' , 0 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (144 , 58 , 56 , 377 , '2013-10-25' , 0 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (145 , 99 , 56 , 317 , '2013-10-29' , 1 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (146 , 56 , 57 , 290 , '2013-10-15' , 0 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (147 , 112 , 57 , 437 , '2013-10-20' , 0 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (148 , 180 , 57 , 380 , '2013-10-29' , 4 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (149 , 97 , 58 , 417 , '2013-11-06' , 1 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (150 , 14 , 58 , 84 , '2013-10-19' , 0 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (151 , 23 , 58 , 66 , '2013-10-16' , 0 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (152 , 121 , 58 , 57 , '2013-11-17' , 0 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (153 , 13 , 59 , 9 , '2013-12-01' , 0 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (154 , 82 , 59 , 425 , '2013-11-23' , 1 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (155 , 110 , 59 , 54 , '2013-12-02' , 1 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (156 , 119 , 60 , 310 , '2013-12-04' , 0 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (157 , 58 , 60 , 110 , '2013-12-10' , 0 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (158 , 35 , 61 , 132 , '2013-12-01' , 1 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (159 , 91 , 61 , 84 , '2013-11-20' , 1 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (160 , 32 , 62 , 424 , '2014-01-01' , 1 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (161 , 92 , 62 , 209 , '2014-01-06' , 1 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (162 , 83 , 63 , 313 , '2013-12-24' , 1 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (163 , 154 , 63 , 219 , '2013-12-23' , 2 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (164 , 32 , 64 , 217 , '2014-01-07' , 0 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (165 , 39 , 64 , 31 , '2013-12-30' , 1 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (166 , 74 , 64 , 90 , '2013-12-31' , 0 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (167 , 96 , 65 , 300 , '2014-01-27' , 2 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (168 , 2 , 65 , 363 , '2014-01-22' , 0 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (169 , 20 , 65 , 412 , '2014-01-16' , 0 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (170 , 94 , 65 , 238 , '2014-01-15' , 1 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (171 , 100 , 66 , 28 , '2014-01-01' , 1 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (172 , 27 , 66 , 295 , '2014-01-14' , 0 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (173 , 38 , 67 , 225 , '2014-02-03' , 0 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (174 , 60 , 67 , 109 , '2014-01-30' , 1 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (175 , 64 , 67 , 456 , '2014-02-03' , 0 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (176 , 145 , 68 , 174 , '2014-02-11' , 2 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (177 , 38 , 69 , 443 , '2014-02-11' , 0 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (178 , 88 , 69 , 381 , '2014-01-17' , 1 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (179 , 20 , 70 , 257 , '2014-01-31' , 0 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (180 , 94 , 70 , 164 , '2014-01-28' , 1 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (181 , 53 , 71 , 69 , '2014-02-01' , 1 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (182 , 95 , 71 , 309 , '2014-02-14' , 0 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (183 , 26 , 72 , 350 , '2014-02-27' , 2 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (184 , 35 , 72 , 122 , '2014-02-20' , 0 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (185 , 74 , 72 , 316 , '2014-02-10' , 0 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (186 , 39 , 73 , 7 , '2014-03-17' , 2 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (187 , 47 , 73 , 21 , '2014-03-13' , 0 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (188 , 17 , 73 , 136 , '2014-03-18' , 0 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (189 , 21 , 73 , 163 , '2014-03-02' , 0 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (190 , 93 , 74 , 4 , '2014-03-28' , 0 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (191 , 16 , 74 , 406 , '2014-03-21' , 0 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (192 , 49 , 74 , 162 , '2014-03-02' , 1 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (193 , 80 , 75 , 394 , '2014-04-21' , 2 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (194 , 199 , 75 , 420 , '2014-03-31' , 2 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (195 , 79 , 76 , 31 , '2014-04-15' , 0 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (196 , 34 , 76 , 51 , '2014-04-22' , 1 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (197 , 56 , 77 , 112 , '2014-04-29' , 2 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (198 , 226 , 77 , 196 , '2014-04-11' , 2 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (199 , 70 , 78 , 183 , '2014-04-03' , 1 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (200 , 59 , 78 , 63 , '2014-04-16' , 2 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (201 , 149 , 79 , 105 , '2014-04-04' , 1 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (202 , 23 , 79 , 121 , '2014-05-03' , 0 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (203 , 188 , 79 , 384 , '2014-04-05' , 0 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (204 , 159 , 80 , 430 , '2014-04-09' , 0 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (205 , 199 , 80 , 442 , '2014-04-17' , 3 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (206 , 133 , 81 , 361 , '2014-05-16' , 0 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (207 , 5 , 81 , 307 , '2014-05-23' , 0 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (208 , 29 , 81 , 370 , '2014-05-17' , 0 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (209 , 75 , 81 , 364 , '2014-05-16' , 1 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (210 , 107 , 82 , 301 , '2014-05-20' , 1 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (211 , 42 , 82 , 78 , '2014-05-01' , 0 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (212 , 75 , 83 , 440 , '2014-05-12' , 0 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (213 , 61 , 83 , 271 , '2014-06-01' , 2 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (214 , 72 , 83 , 327 , '2014-05-29' , 0 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (215 , 41 , 84 , 196 , '2014-05-21' , 1 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (216 , 6 , 84 , 418 , '2014-05-01' , 0 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (217 , 29 , 84 , 116 , '2014-05-10' , 0 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (218 , 75 , 84 , 386 , '2014-05-06' , 0 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (219 , 112 , 85 , 436 , '2014-05-07' , 1 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (220 , 99 , 86 , 447 , '2014-05-25' , 1 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (221 , 181 , 86 , 146 , '2014-05-27' , 1 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (222 , 139 , 87 , 391 , '2014-05-03' , 0 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (223 , 102 , 87 , 129 , '2014-05-13' , 1 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (224 , 89 , 88 , 35 , '2014-06-07' , 0 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (225 , 220 , 88 , 151 , '2014-06-07' , 2 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (226 , 75 , 89 , 14 , '2014-06-21' , 1 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (227 , 23 , 89 , 15 , '2014-06-02' , 3 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (228 , 105 , 89 , 396 , '2014-06-08' , 1 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (229 , 160 , 89 , 68 , '2014-06-03' , 3 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (230 , 43 , 90 , 2 , '2014-05-31' , 0 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (231 , 16 , 90 , 268 , '2014-06-17' , 0 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (232 , 61 , 90 , 286 , '2014-06-12' , 0 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (233 , 105 , 91 , 375 , '2014-05-30' , 4 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (234 , 138 , 91 , 83 , '2014-05-25' , 1 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (235 , 91 , 92 , 43 , '2014-06-07' , 2 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (236 , 53 , 92 , 24 , '2014-07-05' , 0 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (237 , 22 , 92 , 93 , '2014-06-21' , 0 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (238 , 167 , 92 , 367 , '2014-06-27' , 4 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (239 , 90 , 93 , 311 , '2014-07-05' , 0 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (240 , 89 , 93 , 339 , '2014-06-16' , 0 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (241 , 59 , 94 , 426 , '2014-07-11' , 2 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (242 , 91 , 94 , 439 , '2014-06-23' , 0 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (243 , 76 , 95 , 392 , '2014-06-18' , 0 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (244 , 110 , 95 , 286 , '2014-06-18' , 0 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (245 , 60 , 96 , 348 , '2014-06-16' , 0 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (246 , 121 , 96 , 205 , '2014-07-14' , 1 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (247 , 25 , 96 , 115 , '2014-06-15' , 0 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (248 , 221 , 96 , 129 , '2014-06-23' , 4 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (249 , 196 , 97 , 416 , '2014-07-11' , 3 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (250 , 79 , 97 , 308 , '2014-07-16' , 0 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (251 , 5 , 98 , 424 , '2014-08-11' , 0 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (252 , 123 , 98 , 252 , '2014-07-15' , 1 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (253 , 191 , 98 , 348 , '2014-07-25' , 1 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (254 , 220 , 99 , 361 , '2014-07-21' , 1 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (255 , 82 , 99 , 181 , '2014-08-07' , 0 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (256 , 22 , 100 , 44 , '2014-08-18' , 0 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (257 , 130 , 100 , 230 , '2014-08-02' , 1 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (258 , 188 , 100 , 101 , '2014-08-21' , 6 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (259 , 144 , 101 , 45 , '2014-09-06' , 1 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (260 , 25 , 102 , 426 , '2014-08-25' , 1 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (261 , 46 , 102 , 80 , '2014-08-31' , 0 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (262 , 50 , 102 , 155 , '2014-09-08' , 1 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (263 , 115 , 103 , 4 , '2014-09-08' , 0 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (264 , 4 , 103 , 328 , '2014-09-07' , 0 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (265 , 115 , 103 , 18 , '2014-09-15' , 1 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (266 , 42 , 104 , 71 , '2014-09-06' , 0 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (267 , 99 , 104 , 102 , '2014-09-14' , 1 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (268 , 82 , 105 , 442 , '2014-09-24' , 0 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (269 , 29 , 105 , 152 , '2014-09-12' , 0 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (270 , 120 , 106 , 208 , '2014-09-23' , 2 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (271 , 78 , 107 , 4 , '2014-10-02' , 2 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (272 , 72 , 107 , 300 , '2014-09-20' , 3 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (273 , 34 , 107 , 355 , '2014-09-14' , 0 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (274 , 88 , 107 , 156 , '2014-09-18' , 0 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (275 , 29 , 108 , 176 , '2014-09-30' , 2 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (276 , 71 , 108 , 265 , '2014-10-14' , 2 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (277 , 181 , 108 , 388 , '2014-10-26' , 0 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (278 , 181 , 109 , 307 , '2014-11-04' , 1 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (279 , 80 , 109 , 371 , '2014-11-06' , 2 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (280 , 16 , 110 , 395 , '2014-10-29' , 0 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (281 , 156 , 110 , 6 , '2014-10-26' , 1 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (282 , 113 , 110 , 310 , '2014-10-29' , 0 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (283 , 24 , 111 , 118 , '2014-10-22' , 0 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (284 , 36 , 111 , 315 , '2014-10-24' , 0 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (285 , 57 , 111 , 138 , '2014-11-11' , 0 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (286 , 123 , 111 , 444 , '2014-10-12' , 0 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (287 , 186 , 112 , 86 , '2014-11-03' , 2 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (288 , 54 , 112 , 348 , '2014-11-03' , 0 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (289 , 14 , 113 , 445 , '2014-11-12' , 0 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (290 , 18 , 113 , 143 , '2014-10-14' , 0 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (291 , 4 , 113 , 70 , '2014-10-18' , 0 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (292 , 3 , 113 , 306 , '2014-11-04' , 0 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (293 , 53 , 113 , 427 , '2014-11-10' , 0 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (294 , 29 , 113 , 260 , '2014-10-13' , 0 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (295 , 5 , 114 , 137 , '2014-11-06' , 0 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (296 , 180 , 114 , 370 , '2014-11-15' , 2 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (297 , 146 , 114 , 432 , '2014-11-03' , 2 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (298 , 122 , 115 , 393 , '2014-11-03' , 1 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (299 , 131 , 115 , 149 , '2014-10-23' , 2 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (300 , 121 , 116 , 324 , '2014-11-26' , 1 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (301 , 109 , 116 , 310 , '2014-11-21' , 2 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (302 , 148 , 117 , 21 , '2014-12-11' , 5 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (303 , 54 , 118 , 88 , '2014-11-23' , 1 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (304 , 171 , 118 , 7 , '2014-11-29' , 0 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (305 , 17 , 118 , 12 , '2014-11-19' , 0 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (306 , 9 , 119 , 161 , '2014-12-03' , 0 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (307 , 169 , 119 , 151 , '2014-12-09' , 3 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (308 , 104 , 119 , 150 , '2014-11-15' , 3 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (309 , 75 , 120 , 108 , '2014-12-17' , 1 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (310 , 99 , 120 , 189 , '2014-12-29' , 0 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (311 , 142 , 121 , 458 , '2015-01-01' , 0 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (312 , 22 , 121 , 397 , '2015-01-05' , 0 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (313 , 116 , 121 , 378 , '2014-12-31' , 2 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (314 , 54 , 122 , 114 , '2015-01-07' , 1 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (315 , 23 , 122 , 437 , '2014-12-24' , 0 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (316 , 35 , 122 , 170 , '2014-12-22' , 1 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (317 , 27 , 123 , 425 , '2014-12-23' , 0 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (318 , 198 , 123 , 78 , '2014-12-19' , 3 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (319 , 23 , 123 , 112 , '2014-12-13' , 1 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (320 , 234 , 124 , 231 , '2015-02-01' , 4 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (321 , 54 , 125 , 166 , '2015-01-27' , 0 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (322 , 15 , 125 , 24 , '2015-01-30' , 0 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (323 , 86 , 125 , 129 , '2015-01-25' , 0 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (324 , 135 , 126 , 4 , '2015-01-17' , 2 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (325 , 70 , 126 , 77 , '2015-02-15' , 2 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (326 , 89 , 127 , 353 , '2015-01-19' , 2 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (327 , 109 , 127 , 69 , '2015-02-11' , 0 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (328 , 154 , 127 , 180 , '2015-02-04' , 3 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (329 , 106 , 128 , 469 , '2015-02-08' , 2 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (330 , 39 , 128 , 201 , '2015-02-08' , 0 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (331 , 84 , 129 , 307 , '2015-02-12' , 0 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (332 , 38 , 129 , 9 , '2015-02-05' , 0 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (333 , 96 , 130 , 436 , '2015-03-04' , 1 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (334 , 183 , 130 , 335 , '2015-02-07' , 2 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (335 , 84 , 131 , 155 , '2015-02-15' , 1 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (336 , 74 , 131 , 3 , '2015-02-13' , 0 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (337 , 190 , 132 , 455 , '2015-02-26' , 2 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (338 , 185 , 133 , 78 , '2015-02-20' , 2 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (339 , 216 , 134 , 314 , '2015-03-02' , 1 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (340 , 112 , 134 , 45 , '2015-03-19' , 1 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (341 , 192 , 135 , 297 , '2015-03-02' , 5 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (342 , 77 , 135 , 389 , '2015-03-05' , 0 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (343 , 119 , 136 , 171 , '2015-03-10' , 3 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (344 , 142 , 137 , 189 , '2015-03-23' , 1 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (345 , 223 , 137 , 5 , '2015-03-10' , 6 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (346 , 219 , 138 , 300 , '2015-04-02' , 1 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (347 , 217 , 138 , 148 , '2015-03-20' , 2 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (348 , 53 , 139 , 229 , '2015-04-12' , 0 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (349 , 74 , 139 , 63 , '2015-04-08' , 0 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (350 , 30 , 139 , 317 , '2015-03-24' , 1 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (351 , 82 , 140 , 296 , '2015-04-03' , 0 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (352 , 7 , 140 , 216 , '2015-04-02' , 0 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (353 , 18 , 140 , 311 , '2015-04-06' , 0 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (354 , 25 , 140 , 118 , '2015-04-03' , 1 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (355 , 43 , 141 , 290 , '2015-04-17' , 0 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (356 , 24 , 141 , 406 , '2015-04-11' , 1 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (357 , 183 , 141 , 427 , '2015-04-13' , 1 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (358 , 62 , 142 , 20 , '2015-04-08' , 2 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (359 , 149 , 142 , 50 , '2015-04-26' , 1 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (360 , 63 , 143 , 307 , '2015-04-04' , 0 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (361 , 58 , 143 , 302 , '2015-04-28' , 0 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (362 , 46 , 143 , 236 , '2015-04-18' , 1 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (363 , 200 , 144 , 270 , '2015-04-05' , 3 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (364 , 186 , 144 , 357 , '2015-04-17' , 2 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (365 , 35 , 145 , 459 , '2015-05-12' , 0 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (366 , 54 , 145 , 127 , '2015-05-18' , 0 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (367 , 52 , 145 , 136 , '2015-04-20' , 0 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (368 , 3 , 145 , 445 , '2015-04-20' , 0 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (369 , 191 , 145 , 15 , '2015-04-24' , 2 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (370 , 52 , 146 , 98 , '2015-05-20' , 1 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (371 , 59 , 146 , 141 , '2015-05-10' , 0 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (372 , 90 , 146 , 460 , '2015-05-13' , 1 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (373 , 229 , 147 , 236 , '2015-05-13' , 2 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (374 , 32 , 147 , 206 , '2015-05-11' , 0 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (375 , 103 , 148 , 152 , '2015-06-15' , 0 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (376 , 102 , 148 , 58 , '2015-06-20' , 1 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (377 , 214 , 149 , 387 , '2015-05-30' , 0 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (378 , 133 , 149 , 410 , '2015-06-03' , 1 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (379 , 13 , 150 , 225 , '2015-05-26' , 0 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (380 , 150 , 150 , 114 , '2015-06-07' , 2 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (381 , 17 , 150 , 196 , '2015-06-18' , 0 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (382 , 90 , 150 , 214 , '2015-05-31' , 0 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (383 , 81 , 151 , 442 , '2015-06-07' , 2 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (384 , 94 , 151 , 370 , '2015-06-24' , 1 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (385 , 53 , 151 , 232 , '2015-06-01' , 2 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (386 , 146 , 151 , 188 , '2015-05-31' , 2 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (387 , 98 , 152 , 228 , '2015-06-22' , 2 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (388 , 118 , 152 , 101 , '2015-06-19' , 0 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (389 , 75 , 153 , 114 , '2015-06-06' , 0 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (390 , 103 , 153 , 356 , '2015-06-24' , 1 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (391 , 136 , 154 , 52 , '2015-07-11' , 1 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (392 , 127 , 154 , 219 , '2015-06-19' , 0 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (393 , 126 , 155 , 113 , '2015-07-18' , 0 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (394 , 79 , 155 , 449 , '2015-06-21' , 0 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (395 , 92 , 156 , 431 , '2015-07-07' , 0 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (396 , 98 , 156 , 453 , '2015-07-15' , 0 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (397 , 102 , 157 , 125 , '2015-06-25' , 3 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (398 , 133 , 157 , 95 , '2015-07-03' , 1 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (399 , 24 , 158 , 452 , '2015-07-17' , 0 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (400 , 33 , 158 , 445 , '2015-07-12' , 1 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (401 , 11 , 158 , 369 , '2015-07-19' , 0 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (402 , 142 , 158 , 470 , '2015-08-06' , 2 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (403 , 90 , 159 , 273 , '2015-07-30' , 2 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (404 , 247 , 159 , 118 , '2015-07-10' , 4 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (405 , 131 , 160 , 151 , '2015-07-22' , 2 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (406 , 105 , 160 , 18 , '2015-07-23' , 3 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (407 , 26 , 161 , 236 , '2015-08-08' , 0 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (408 , 121 , 161 , 178 , '2015-08-06' , 4 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (409 , 96 , 162 , 400 , '2015-08-28' , 0 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (410 , 54 , 162 , 225 , '2015-08-24' , 0 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (411 , 97 , 162 , 46 , '2015-08-28' , 0 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (412 , 33 , 163 , 364 , '2015-08-30' , 0 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (413 , 36 , 163 , 364 , '2015-09-05' , 0 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (414 , 106 , 163 , 382 , '2015-09-02' , 0 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (415 , 55 , 163 , 67 , '2015-08-25' , 0 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (416 , 1 , 163 , 233 , '2015-08-05' , 0 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (417 , 100 , 164 , 208 , '2015-08-28' , 1 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (418 , 12 , 164 , 375 , '2015-08-30' , 0 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (419 , 158 , 164 , 320 , '2015-08-08' , 0 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (420 , 34 , 165 , 94 , '2015-08-21' , 0 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (421 , 13 , 165 , 219 , '2015-09-04' , 1 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (422 , 134 , 165 , 41 , '2015-09-08' , 1 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (423 , 14 , 166 , 216 , '2015-08-23' , 0 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (424 , 144 , 166 , 319 , '2015-08-25' , 0 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (425 , 78 , 166 , 310 , '2015-08-19' , 3 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (426 , 126 , 167 , 36 , '2015-09-04' , 2 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (427 , 170 , 167 , 460 , '2015-09-01' , 1 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (428 , 5 , 168 , 58 , '2015-08-25' , 0 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (429 , 243 , 168 , 378 , '2015-09-03' , 1 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (430 , 98 , 169 , 89 , '2015-08-30' , 0 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (431 , 44 , 169 , 307 , '2015-09-02' , 1 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (432 , 30 , 170 , 417 , '2015-08-29' , 0 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (433 , 143 , 170 , 197 , '2015-09-11' , 0 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (434 , 18 , 170 , 286 , '2015-09-16' , 0 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (435 , 196 , 170 , 22 , '2015-09-23' , 0 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (436 , 48 , 171 , 36 , '2015-08-26' , 1 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (437 , 78 , 171 , 294 , '2015-09-15' , 1 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (438 , 52 , 172 , 61 , '2015-10-07' , 0 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (439 , 8 , 172 , 117 , '2015-09-18' , 0 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (440 , 116 , 172 , 186 , '2015-09-18' , 2 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (441 , 57 , 173 , 179 , '2015-09-28' , 0 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (442 , 85 , 173 , 452 , '2015-10-17' , 0 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (443 , 139 , 174 , 378 , '2015-10-11' , 1 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (444 , 74 , 175 , 336 , '2015-10-15' , 1 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (445 , 111 , 175 , 391 , '2015-09-25' , 1 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (446 , 32 , 176 , 198 , '2015-09-24' , 0 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (447 , 41 , 176 , 341 , '2015-10-13' , 0 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (448 , 79 , 176 , 200 , '2015-10-07' , 0 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (449 , 131 , 177 , 313 , '2015-10-23' , 0 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (450 , 112 , 177 , 260 , '2015-10-05' , 0 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (451 , 39 , 178 , 309 , '2015-10-19' , 0 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (452 , 47 , 178 , 441 , '2015-10-09' , 0 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (453 , 11 , 178 , 403 , '2015-10-03' , 0 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (454 , 75 , 178 , 52 , '2015-09-30' , 0 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (455 , 53 , 179 , 83 , '2015-10-26' , 0 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (456 , 116 , 179 , 278 , '2015-10-24' , 1 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (457 , 96 , 179 , 363 , '2015-10-16' , 1 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (458 , 94 , 180 , 126 , '2015-10-28' , 0 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (459 , 33 , 180 , 40 , '2015-10-27' , 0 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (460 , 103 , 180 , 107 , '2015-11-10' , 1 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (461 , 245 , 181 , 456 , '2015-11-08' , 1 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (462 , 26 , 182 , 113 , '2015-10-25' , 1 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (463 , 145 , 182 , 466 , '2015-11-06' , 1 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (464 , 16 , 182 , 11 , '2015-11-06' , 1 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (465 , 151 , 182 , 87 , '2015-11-10' , 2 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (466 , 21 , 183 , 247 , '2015-11-16' , 0 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (467 , 21 , 183 , 133 , '2015-11-12' , 0 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (468 , 36 , 183 , 299 , '2015-11-02' , 0 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (469 , 138 , 183 , 199 , '2015-11-23' , 1 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (470 , 171 , 183 , 20 , '2015-11-03' , 0 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (471 , 109 , 184 , 372 , '2015-11-16' , 0 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (472 , 56 , 184 , 445 , '2015-11-02' , 1 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (473 , 124 , 185 , 366 , '2015-11-20' , 1 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (474 , 162 , 185 , 105 , '2015-11-21' , 0 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (475 , 109 , 186 , 268 , '2015-12-20' , 3 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (476 , 31 , 186 , 288 , '2015-12-20' , 0 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (477 , 67 , 187 , 305 , '2015-11-28' , 0 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (478 , 46 , 187 , 335 , '2015-11-25' , 1 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (479 , 15 , 188 , 134 , '2016-01-01' , 0 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (480 , 2 , 188 , 136 , '2015-12-07' , 0 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (481 , 150 , 188 , 319 , '2015-12-03' , 0 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (482 , 43 , 189 , 453 , '2015-12-13' , 0 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (483 , 95 , 189 , 450 , '2015-12-25' , 1 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (484 , 169 , 190 , 410 , '2015-12-31' , 3 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (485 , 14 , 190 , 321 , '2016-01-05' , 2 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (486 , 111 , 190 , 161 , '2015-12-17' , 0 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (487 , 103 , 191 , 122 , '2015-12-29' , 3 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (488 , 27 , 191 , 398 , '2016-01-26' , 0 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (489 , 12 , 191 , 248 , '2016-01-10' , 0 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (490 , 84 , 191 , 349 , '2016-01-24' , 0 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (491 , 51 , 192 , 58 , '2016-01-31' , 1 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (492 , 94 , 192 , 251 , '2016-01-11' , 0 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (493 , 88 , 192 , 307 , '2016-01-16' , 1 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (494 , 10 , 193 , 204 , '2016-01-24' , 0 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (495 , 23 , 193 , 450 , '2016-02-03' , 0 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (496 , 48 , 193 , 373 , '2016-02-08' , 0 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (497 , 55 , 193 , 454 , '2016-02-02' , 1 )
