set identity_insert [dbo].[Conference] on;
INSERT INTO [dbo].[Conference] (ConferenceID, BeginDate, EndDate, ConferenceName) 
	VALUES (1 , '2013-02-07' , '2013-02-08' , 'ICASSP - International Conference on Acoustics, Speech, and Signal Processing ' )
INSERT INTO [dbo].[Conference] (ConferenceID, BeginDate, EndDate, ConferenceName) 
	VALUES (2 , '2013-02-14' , '2013-02-15' , 'INFOCOM - IEEE INFOCOM ' )
INSERT INTO [dbo].[Conference] (ConferenceID, BeginDate, EndDate, ConferenceName) 
	VALUES (3 , '2013-03-02' , '2013-03-05' , 'Theory of Cryptography ' )
INSERT INTO [dbo].[Conference] (ConferenceID, BeginDate, EndDate, ConferenceName) 
	VALUES (4 , '2013-03-24' , '2013-03-25' , 'HICSS - Hawaii International Conference on System Sciences ' )
INSERT INTO [dbo].[Conference] (ConferenceID, BeginDate, EndDate, ConferenceName) 
	VALUES (5 , '2013-04-05' , '2013-04-05' , 'CHI - Computer Human Interaction ' )
INSERT INTO [dbo].[Conference] (ConferenceID, BeginDate, EndDate, ConferenceName) 
	VALUES (6 , '2013-04-04' , '2013-04-07' , 'ISIT - IEEE International Symposium on Information Theory ' )
INSERT INTO [dbo].[Conference] (ConferenceID, BeginDate, EndDate, ConferenceName) 
	VALUES (7 , '2013-05-02' , '2013-05-05' , 'ICSE - International Conference on Software Engineering ' )
INSERT INTO [dbo].[Conference] (ConferenceID, BeginDate, EndDate, ConferenceName) 
	VALUES (8 , '2013-05-25' , '2013-05-26' , 'ICDE - International Conference on Data Engineering ' )
INSERT INTO [dbo].[Conference] (ConferenceID, BeginDate, EndDate, ConferenceName) 
	VALUES (9 , '2013-06-06' , '2013-06-06' , 'SAC - ACM Symposium on Applied Computing ' )
INSERT INTO [dbo].[Conference] (ConferenceID, BeginDate, EndDate, ConferenceName) 
	VALUES (10 , '2013-06-21' , '2013-06-24' , 'WWW - World Wide Web Conference Series ' )
INSERT INTO [dbo].[Conference] (ConferenceID, BeginDate, EndDate, ConferenceName) 
	VALUES (11 , '2013-06-24' , '2013-06-26' , 'FGR - IEEE International Conference on Automatic Face and Gesture Recognition ' )
INSERT INTO [dbo].[Conference] (ConferenceID, BeginDate, EndDate, ConferenceName) 
	VALUES (12 , '2013-07-07' , '2013-07-10' , 'HPCA - International Symposium on High-Performance Computer Architecture ' )
INSERT INTO [dbo].[Conference] (ConferenceID, BeginDate, EndDate, ConferenceName) 
	VALUES (13 , '2013-07-20' , '2013-07-21' , 'WSDM - Web Search and Data Mining ' )
INSERT INTO [dbo].[Conference] (ConferenceID, BeginDate, EndDate, ConferenceName) 
	VALUES (14 , '2013-08-07' , '2013-08-09' , 'S&P - IEEE Symposium on Security and Privacy ' )
INSERT INTO [dbo].[Conference] (ConferenceID, BeginDate, EndDate, ConferenceName) 
	VALUES (15 , '2013-08-20' , '2013-08-22' , 'AMS - Asia International Conference on Modeling & Simulation ' )
INSERT INTO [dbo].[Conference] (ConferenceID, BeginDate, EndDate, ConferenceName) 
	VALUES (16 , '2013-09-21' , '2013-09-24' , 'CIDR - Conference on Innovative Data Systems Research ' )
INSERT INTO [dbo].[Conference] (ConferenceID, BeginDate, EndDate, ConferenceName) 
	VALUES (17 , '2013-09-25' , '2013-09-25' , 'ASPLOS - Architectural Support for Programming Languages and Operating Systems ' )
INSERT INTO [dbo].[Conference] (ConferenceID, BeginDate, EndDate, ConferenceName) 
	VALUES (18 , '2013-10-17' , '2013-10-19' , 'EUROCRYPT - Theory and Application of Cryptographic Techniques ' )
INSERT INTO [dbo].[Conference] (ConferenceID, BeginDate, EndDate, ConferenceName) 
	VALUES (19 , '2013-10-31' , '2013-11-03' , 'VMCAI - Verification, Model Checking and Abstract Interpretation  ' )
INSERT INTO [dbo].[Conference] (ConferenceID, BeginDate, EndDate, ConferenceName) 
	VALUES (20 , '2013-11-17' , '2013-11-17' , 'EUROSYS - EuroSys Conference ' )
INSERT INTO [dbo].[Conference] (ConferenceID, BeginDate, EndDate, ConferenceName) 
	VALUES (21 , '2013-11-17' , '2013-11-20' , 'ECRTS - Euromicro Conference on Real-Time Systems ' )
INSERT INTO [dbo].[Conference] (ConferenceID, BeginDate, EndDate, ConferenceName) 
	VALUES (22 , '2013-12-14' , '2013-12-15' , 'NSDI - Networked Systems Design and Implementation ' )
INSERT INTO [dbo].[Conference] (ConferenceID, BeginDate, EndDate, ConferenceName) 
	VALUES (23 , '2013-12-22' , '2013-12-22' , 'IROS - International Conference on Intelligent RObots and Systems - IROS ' )
INSERT INTO [dbo].[Conference] (ConferenceID, BeginDate, EndDate, ConferenceName) 
	VALUES (24 , '2014-01-13' , '2014-01-15' , 'WCNC - Wireless Communications and Networking, IEEE Conference ' )
INSERT INTO [dbo].[Conference] (ConferenceID, BeginDate, EndDate, ConferenceName) 
	VALUES (25 , '2014-02-01' , '2014-02-02' , 'ISCAS - IEEE International Symposium on Circuits and Systems ' )
INSERT INTO [dbo].[Conference] (ConferenceID, BeginDate, EndDate, ConferenceName) 
	VALUES (26 , '2014-02-17' , '2014-02-20' , 'ISNN - International Symposium on Neural Networks ' )
INSERT INTO [dbo].[Conference] (ConferenceID, BeginDate, EndDate, ConferenceName) 
	VALUES (27 , '2014-02-21' , '2014-02-21' , 'ICCV - International Conference on Computer Vision ' )
INSERT INTO [dbo].[Conference] (ConferenceID, BeginDate, EndDate, ConferenceName) 
	VALUES (28 , '2014-03-05' , '2014-03-05' , 'AINA - Advanced Information Networking and Applications ' )
INSERT INTO [dbo].[Conference] (ConferenceID, BeginDate, EndDate, ConferenceName) 
	VALUES (29 , '2014-03-22' , '2014-03-22' , 'CVPR - Computer Vision and Pattern Recognition ' )
INSERT INTO [dbo].[Conference] (ConferenceID, BeginDate, EndDate, ConferenceName) 
	VALUES (30 , '2014-04-04' , '2014-04-04' , 'IEEE International Conference on Pervasive Computing and Communications ' )
INSERT INTO [dbo].[Conference] (ConferenceID, BeginDate, EndDate, ConferenceName) 
	VALUES (31 , '2014-05-05' , '2014-05-08' , 'ASP-DAC - Asia and South Pacific Design Automation Conference ' )
INSERT INTO [dbo].[Conference] (ConferenceID, BeginDate, EndDate, ConferenceName) 
	VALUES (32 , '2014-05-09' , '2014-05-10' , 'ICST - International Conference on Software Testing, Verification, and Validation ' )
INSERT INTO [dbo].[Conference] (ConferenceID, BeginDate, EndDate, ConferenceName) 
	VALUES (33 , '2014-06-03' , '2014-06-05' , 'ETFA - Emerging Technologies and Factory Automation ' )
INSERT INTO [dbo].[Conference] (ConferenceID, BeginDate, EndDate, ConferenceName) 
	VALUES (34 , '2014-05-29' , '2014-06-01' , 'INFOCOM WKSHPS - IEEE Conference on Computer Communications Workshops, INFOCOM Wksps ' )
INSERT INTO [dbo].[Conference] (ConferenceID, BeginDate, EndDate, ConferenceName) 
	VALUES (35 , '2014-06-23' , '2014-06-26' , 'ISQED - International Symposium on Quality Electronic Design ' )
INSERT INTO [dbo].[Conference] (ConferenceID, BeginDate, EndDate, ConferenceName) 
	VALUES (36 , '2014-07-12' , '2014-07-14' , 'IV - Intelligent Vehicle, IEEE Symposium ' )
INSERT INTO [dbo].[Conference] (ConferenceID, BeginDate, EndDate, ConferenceName) 
	VALUES (37 , '2014-07-16' , '2014-07-17' , 'RWS formerly RAWCON - IEEE Radio and Wireless Symposium formerly ' )
INSERT INTO [dbo].[Conference] (ConferenceID, BeginDate, EndDate, ConferenceName) 
	VALUES (38 , '2014-08-13' , '2014-08-14' , 'ICALT - International Conference on Advanced Learning Technologies ' )
INSERT INTO [dbo].[Conference] (ConferenceID, BeginDate, EndDate, ConferenceName) 
	VALUES (39 , '2014-08-22' , '2014-08-22' , 'ISCI - IEEE Symposium on Computers & Informatics ' )
INSERT INTO [dbo].[Conference] (ConferenceID, BeginDate, EndDate, ConferenceName) 
	VALUES (40 , '2014-09-04' , '2014-09-04' , 'COMSNETS - International Communication Systems and Networks and Workshops ' )
INSERT INTO [dbo].[Conference] (ConferenceID, BeginDate, EndDate, ConferenceName) 
	VALUES (41 , '2014-09-19' , '2014-09-22' , 'ISCC - International Symposium on Computers and Communications ' )
INSERT INTO [dbo].[Conference] (ConferenceID, BeginDate, EndDate, ConferenceName) 
	VALUES (42 , '2014-10-14' , '2014-10-16' , 'Integrated Network Management ' )
INSERT INTO [dbo].[Conference] (ConferenceID, BeginDate, EndDate, ConferenceName) 
	VALUES (43 , '2014-10-29' , '2014-10-29' , 'Parallel, Distributed and Network-Based Processing ' )
INSERT INTO [dbo].[Conference] (ConferenceID, BeginDate, EndDate, ConferenceName) 
	VALUES (44 , '2014-11-14' , '2014-11-15' , 'VLSI Design ' )
INSERT INTO [dbo].[Conference] (ConferenceID, BeginDate, EndDate, ConferenceName) 
	VALUES (45 , '2014-11-15' , '2014-11-17' , 'DCC - Data Compression Conference ' )
INSERT INTO [dbo].[Conference] (ConferenceID, BeginDate, EndDate, ConferenceName) 
	VALUES (46 , '2014-11-25' , '2014-11-26' , 'WACV - Workshop on Applications of Computer Vision ' )
INSERT INTO [dbo].[Conference] (ConferenceID, BeginDate, EndDate, ConferenceName) 
	VALUES (47 , '2014-12-17' , '2014-12-20' , 'HRI - Human-Robot Interaction ' )
INSERT INTO [dbo].[Conference] (ConferenceID, BeginDate, EndDate, ConferenceName) 
	VALUES (48 , '2015-01-01' , '2015-01-01' , 'Information Theory and Applications ' )
INSERT INTO [dbo].[Conference] (ConferenceID, BeginDate, EndDate, ConferenceName) 
	VALUES (49 , '2015-01-09' , '2015-01-11' , 'EvoWorkshops ' )
INSERT INTO [dbo].[Conference] (ConferenceID, BeginDate, EndDate, ConferenceName) 
	VALUES (50 , '2015-02-09' , '2015-02-10' , 'IP - ICO International Conference on Information Photonics ' )
INSERT INTO [dbo].[Conference] (ConferenceID, BeginDate, EndDate, ConferenceName) 
	VALUES (51 , '2015-02-20' , '2015-02-23' , 'SACI - Applied Computational Intelligence and Informatics ' )
INSERT INTO [dbo].[Conference] (ConferenceID, BeginDate, EndDate, ConferenceName) 
	VALUES (52 , '2015-03-07' , '2015-03-07' , 'CSCW - Conference on Computer Supported Cooperative Work ' )
INSERT INTO [dbo].[Conference] (ConferenceID, BeginDate, EndDate, ConferenceName) 
	VALUES (53 , '2015-03-20' , '2015-03-23' , 'SODA - ACM-SIAM Symposium on Discrete Algorithms ' )
INSERT INTO [dbo].[Conference] (ConferenceID, BeginDate, EndDate, ConferenceName) 
	VALUES (54 , '2015-04-05' , '2015-04-06' , 'ISADS - International Symposium on Autonomous Decentralized Systems ' )
INSERT INTO [dbo].[Conference] (ConferenceID, BeginDate, EndDate, ConferenceName) 
	VALUES (55 , '2015-04-14' , '2015-04-16' , 'ASRU - IEEE Workshop on Automatic Speech Recognition and Understanding ' )
INSERT INTO [dbo].[Conference] (ConferenceID, BeginDate, EndDate, ConferenceName) 
	VALUES (56 , '2015-04-24' , '2015-04-25' , 'IUI - Intelligent User Interfaces ' )
INSERT INTO [dbo].[Conference] (ConferenceID, BeginDate, EndDate, ConferenceName) 
	VALUES (57 , '2015-05-08' , '2015-05-10' , 'VLSI-DAT - International Symposium on VLSI Design, Automation and Test ' )
INSERT INTO [dbo].[Conference] (ConferenceID, BeginDate, EndDate, ConferenceName) 
	VALUES (58 , '2015-05-24' , '2015-05-26' , 'ICDCS - International Conference on Distributed Computing Systems ' )
INSERT INTO [dbo].[Conference] (ConferenceID, BeginDate, EndDate, ConferenceName) 
	VALUES (59 , '2015-06-27' , '2015-06-30' , 'DySPAN - IEEE International Symposium on New Frontiers in Dynamic Spectrum Access Networks ' )
INSERT INTO [dbo].[Conference] (ConferenceID, BeginDate, EndDate, ConferenceName) 
	VALUES (60 , '2015-07-05' , '2015-07-06' , 'CICLing - Conference on Intelligent Text Processing and Computational Linguistics ' )
INSERT INTO [dbo].[Conference] (ConferenceID, BeginDate, EndDate, ConferenceName) 
	VALUES (61 , '2015-07-18' , '2015-07-18' , 'BTW - Datenbanksysteme in Büro, Technik und Wissenschaft(German Database Conference) ' )
INSERT INTO [dbo].[Conference] (ConferenceID, BeginDate, EndDate, ConferenceName) 
	VALUES (62 , '2015-07-23' , '2015-07-25' , 'WIOPT - Modeling and Optimization in Mobile, Ad-Hoc and Wireless Networks ' )
INSERT INTO [dbo].[Conference] (ConferenceID, BeginDate, EndDate, ConferenceName) 
	VALUES (63 , '2015-08-13' , '2015-08-16' , 'FPGA - Symposium on Field Programmable Gate Arrays ' )
INSERT INTO [dbo].[Conference] (ConferenceID, BeginDate, EndDate, ConferenceName) 
	VALUES (64 , '2015-09-08' , '2015-09-11' , 'formerly Asia-Pacific APVIS - Visualization Symposium, Pacific Asia-Pacific ' )
INSERT INTO [dbo].[Conference] (ConferenceID, BeginDate, EndDate, ConferenceName) 
	VALUES (65 , '2015-09-22' , '2015-09-25' , 'RECOMB - Research in Computational Molecular Biology ' )
INSERT INTO [dbo].[Conference] (ConferenceID, BeginDate, EndDate, ConferenceName) 
	VALUES (66 , '2015-09-27' , '2015-09-28' , 'IWQoS - International Workshop on Quality of Service ' )
INSERT INTO [dbo].[Conference] (ConferenceID, BeginDate, EndDate, ConferenceName) 
	VALUES (67 , '2015-10-23' , '2015-10-26' , 'SOFSEM - Conference on Current Trends in Theory and Practice of Informatics ' )
INSERT INTO [dbo].[Conference] (ConferenceID, BeginDate, EndDate, ConferenceName) 
	VALUES (68 , '2015-10-28' , '2015-10-31' , 'PPoPP - Principles and Practice of Parallel Programming ' )
INSERT INTO [dbo].[Conference] (ConferenceID, BeginDate, EndDate, ConferenceName) 
	VALUES (69 , '2015-11-21' , '2015-11-23' , 'CNDS - International Symposium on Computer Networks and Distributed Systems ' )
INSERT INTO [dbo].[Conference] (ConferenceID, BeginDate, EndDate, ConferenceName) 
	VALUES (70 , '2015-11-29' , '2015-12-01' , 'ICECCS - International Conference on Engineering of Complex Computer Systems ' )
INSERT INTO [dbo].[Conference] (ConferenceID, BeginDate, EndDate, ConferenceName) 
	VALUES (71 , '2015-12-26' , '2015-12-27' , 'Pacific Symposium on Biocomputing ' )
INSERT INTO [dbo].[Conference] (ConferenceID, BeginDate, EndDate, ConferenceName) 
	VALUES (72 , '2016-01-04' , '2016-01-05' , 'WEA - Workshop on Experimental and Efficient Algorithms ' )
INSERT INTO [dbo].[Conference] (ConferenceID, BeginDate, EndDate, ConferenceName) 
	VALUES (73 , '2016-01-15' , '2016-01-15' , 'PKC - Public Key Cryptography ' )
INSERT INTO [dbo].[Conference] (ConferenceID, BeginDate, EndDate, ConferenceName) 
	VALUES (74 , '2016-02-01' , '2016-02-01' , 'TACAS - Tools and Algorithms for Construction and Analysis of Systems ' )
INSERT INTO [dbo].[Conference] (ConferenceID, BeginDate, EndDate, ConferenceName) 
	VALUES (75 , '2016-02-15' , '2016-02-16' , 'FoSSaCS - Foundations of Software Science and Computation Structure ' )
