f1 = open('Insert/Customer.sql').read().splitlines()
f2 = open('Insert/Person.sql').read().splitlines()
f3 = open('Insert/Conference.sql').read().splitlines()
f4 = open('Insert/ConferenceDay.sql').read().splitlines()
f5 = open('Insert/Price.sql').read().splitlines()
f6 = open('Insert/ConferenceDayReservation.sql').read().splitlines()
f7 = open('Insert/Workshop.sql').read().splitlines()
f8 = open('Insert/WorkshopEnrollment.sql').read().splitlines()
f9 = open('Insert/Participants.sql').read().splitlines()
f10 = open('Insert/WorkshopParticipants.sql').read().splitlines()
f11 = open('Insert/Payment.sql').read().splitlines()

ofile = open('Insert/Data.sql', 'w+')
def insert(data):
	for d in data:
		print(d, file = ofile)

print('use Conf', file = ofile)
insert(f1)
insert(f2)
insert(f3)
insert(f4)
insert(f5)
insert(f6)
insert(f7)
insert(f8)
insert(f9)
insert(f10)
insert(f11)