INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (1 , 31 , 1 , 273 , '2013-01-10' , 0 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (2 , 121 , 1 , 291 , '2012-12-24' , 1 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (3 , 168 , 2 , 361 , '2013-01-04' , 0 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (4 , 21 , 2 , 23 , '2013-01-13' , 0 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (5 , 22 , 2 , 185 , '2013-01-01' , 0 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (6 , 46 , 2 , 355 , '2012-12-17' , 0 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (7 , 14 , 3 , 375 , '2013-01-17' , 0 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (8 , 26 , 3 , 312 , '2013-01-13' , 0 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (9 , 145 , 3 , 465 , '2013-01-01' , 2 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (10 , 114 , 4 , 466 , '2013-02-01' , 1 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (11 , 118 , 5 , 290 , '2013-01-25' , 0 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (12 , 138 , 5 , 366 , '2013-01-31' , 1 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (13 , 46 , 6 , 415 , '2013-02-08' , 0 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (14 , 99 , 6 , 385 , '2013-01-24' , 2 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (15 , 69 , 7 , 472 , '2013-01-31' , 0 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (16 , 61 , 7 , 244 , '2013-02-06' , 4 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (17 , 103 , 7 , 330 , '2013-01-19' , 1 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (18 , 77 , 8 , 418 , '2013-02-10' , 2 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (19 , 129 , 8 , 119 , '2013-01-31' , 1 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (20 , 132 , 9 , 162 , '2013-02-05' , 1 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (21 , 121 , 9 , 463 , '2013-02-08' , 0 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (22 , 47 , 10 , 343 , '2013-01-29' , 0 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (23 , 100 , 10 , 385 , '2013-01-29' , 0 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (24 , 15 , 11 , 19 , '2013-01-28' , 0 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (25 , 20 , 11 , 204 , '2013-01-23' , 0 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (26 , 3 , 11 , 282 , '2013-02-05' , 0 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (27 , 7 , 11 , 435 , '2013-01-25' , 0 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (28 , 8 , 11 , 93 , '2013-01-28' , 0 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (29 , 101 , 11 , 347 , '2013-02-05' , 0 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (30 , 75 , 12 , 291 , '2013-02-15' , 0 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (31 , 8 , 12 , 74 , '2013-02-23' , 0 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (32 , 62 , 12 , 284 , '2013-03-04' , 2 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (33 , 138 , 13 , 453 , '2013-03-05' , 3 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (34 , 84 , 13 , 47 , '2013-02-20' , 1 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (35 , 92 , 14 , 271 , '2013-03-18' , 0 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (36 , 30 , 14 , 424 , '2013-02-22' , 0 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (37 , 138 , 14 , 308 , '2013-03-06' , 2 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (38 , 8 , 15 , 95 , '2013-02-20' , 0 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (39 , 183 , 15 , 379 , '2013-02-19' , 6 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (40 , 1 , 15 , 51 , '2013-03-11' , 0 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (41 , 165 , 15 , 368 , '2013-03-06' , 3 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (42 , 93 , 16 , 121 , '2013-03-06' , 2 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (43 , 112 , 16 , 135 , '2013-03-04' , 0 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (44 , 241 , 17 , 29 , '2013-03-07' , 5 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (45 , 133 , 18 , 339 , '2013-04-09' , 3 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (46 , 100 , 18 , 81 , '2013-04-08' , 2 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (47 , 121 , 19 , 45 , '2013-04-04' , 1 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (48 , 70 , 19 , 226 , '2013-04-10' , 0 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (49 , 104 , 20 , 356 , '2013-04-04' , 1 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (50 , 38 , 20 , 90 , '2013-03-15' , 0 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (51 , 75 , 21 , 318 , '2013-04-07' , 1 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (52 , 103 , 21 , 402 , '2013-03-30' , 1 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (53 , 160 , 21 , 306 , '2013-03-29' , 1 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (54 , 74 , 22 , 438 , '2013-04-05' , 1 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (55 , 171 , 22 , 17 , '2013-04-09' , 1 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (56 , 127 , 23 , 446 , '2013-03-17' , 2 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (57 , 62 , 23 , 242 , '2013-03-31' , 0 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (58 , 1 , 23 , 104 , '2013-03-30' , 0 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (59 , 91 , 23 , 322 , '2013-03-22' , 1 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (60 , 82 , 24 , 386 , '2013-04-29' , 0 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (61 , 112 , 24 , 61 , '2013-05-06' , 3 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (62 , 105 , 24 , 398 , '2013-05-17' , 1 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (63 , 74 , 25 , 92 , '2013-04-26' , 0 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (64 , 49 , 25 , 41 , '2013-05-06' , 0 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (65 , 87 , 25 , 283 , '2013-04-21' , 1 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (66 , 147 , 26 , 224 , '2013-04-19' , 1 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (67 , 114 , 26 , 144 , '2013-05-11' , 0 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (68 , 40 , 27 , 380 , '2013-05-13' , 0 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (69 , 146 , 27 , 93 , '2013-05-06' , 2 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (70 , 20 , 28 , 219 , '2013-05-10' , 0 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (71 , 116 , 28 , 228 , '2013-04-20' , 1 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (72 , 134 , 28 , 128 , '2013-04-24' , 1 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (73 , 36 , 29 , 243 , '2013-04-21' , 1 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (74 , 28 , 29 , 394 , '2013-04-22' , 1 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (75 , 235 , 29 , 384 , '2013-05-06' , 0 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (76 , 119 , 30 , 453 , '2013-05-10' , 1 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (77 , 60 , 30 , 441 , '2013-04-27' , 1 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (78 , 31 , 31 , 392 , '2013-04-28' , 0 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (79 , 134 , 31 , 147 , '2013-05-01' , 1 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (80 , 100 , 31 , 205 , '2013-05-17' , 2 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (81 , 69 , 32 , 324 , '2013-05-13' , 0 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (82 , 140 , 32 , 146 , '2013-05-28' , 3 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (83 , 104 , 33 , 407 , '2013-06-03' , 1 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (84 , 75 , 33 , 299 , '2013-05-07' , 1 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (85 , 45 , 34 , 27 , '2013-06-20' , 0 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (86 , 50 , 34 , 403 , '2013-06-01' , 0 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (87 , 53 , 34 , 284 , '2013-06-01' , 1 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (88 , 77 , 35 , 7 , '2013-06-25' , 1 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (89 , 71 , 35 , 310 , '2013-06-18' , 2 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (90 , 39 , 35 , 113 , '2013-06-16' , 2 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (91 , 111 , 36 , 459 , '2013-06-01' , 1 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (92 , 14 , 37 , 339 , '2013-06-17' , 0 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (93 , 54 , 37 , 224 , '2013-06-25' , 0 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (94 , 47 , 37 , 345 , '2013-06-03' , 0 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (95 , 201 , 37 , 204 , '2013-06-01' , 1 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (96 , 100 , 38 , 285 , '2013-06-03' , 1 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (97 , 40 , 38 , 150 , '2013-06-20' , 0 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (98 , 12 , 39 , 472 , '2013-06-23' , 0 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (99 , 122 , 39 , 75 , '2013-06-04' , 1 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (100 , 15 , 39 , 406 , '2013-06-02' , 0 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (101 , 166 , 39 , 376 , '2013-07-01' , 2 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (102 , 191 , 40 , 172 , '2013-06-19' , 3 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (103 , 10 , 40 , 236 , '2013-06-03' , 0 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (104 , 132 , 40 , 291 , '2013-06-06' , 1 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (105 , 93 , 41 , 147 , '2013-06-28' , 0 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (106 , 49 , 41 , 270 , '2013-07-24' , 0 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (107 , 117 , 42 , 75 , '2013-07-18' , 1 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (108 , 16 , 43 , 53 , '2013-07-14' , 0 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (109 , 6 , 43 , 220 , '2013-07-09' , 0 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (110 , 48 , 43 , 142 , '2013-07-16' , 0 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (111 , 38 , 43 , 268 , '2013-07-16' , 0 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (112 , 90 , 43 , 155 , '2013-07-25' , 0 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (113 , 13 , 44 , 143 , '2013-07-22' , 0 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (114 , 120 , 44 , 40 , '2013-08-01' , 2 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (115 , 13 , 44 , 45 , '2013-08-20' , 1 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (116 , 225 , 44 , 369 , '2013-08-13' , 0 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (117 , 95 , 45 , 190 , '2013-08-15' , 1 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (118 , 26 , 45 , 309 , '2013-08-22' , 0 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (119 , 78 , 45 , 377 , '2013-07-26' , 1 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (120 , 114 , 46 , 210 , '2013-08-26' , 1 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (121 , 117 , 46 , 88 , '2013-08-20' , 2 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (122 , 51 , 47 , 181 , '2013-08-10' , 0 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (123 , 98 , 47 , 280 , '2013-07-30' , 0 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (124 , 77 , 48 , 325 , '2013-08-30' , 1 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (125 , 140 , 48 , 362 , '2013-08-23' , 1 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (126 , 24 , 49 , 46 , '2013-09-03' , 0 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (127 , 114 , 49 , 245 , '2013-09-16' , 2 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (128 , 16 , 50 , 462 , '2013-08-27' , 1 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (129 , 108 , 50 , 378 , '2013-09-17' , 1 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (130 , 16 , 51 , 104 , '2013-09-11' , 0 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (131 , 62 , 51 , 7 , '2013-09-05' , 0 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (132 , 85 , 51 , 63 , '2013-09-03' , 2 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (133 , 89 , 52 , 339 , '2013-09-14' , 2 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (134 , 75 , 52 , 181 , '2013-09-25' , 1 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (135 , 244 , 53 , 31 , '2013-09-30' , 3 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (136 , 90 , 54 , 8 , '2013-10-20' , 0 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (137 , 42 , 54 , 162 , '2013-10-12' , 0 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (138 , 5 , 54 , 242 , '2013-10-24' , 0 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (139 , 123 , 54 , 376 , '2013-10-07' , 0 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (140 , 61 , 55 , 13 , '2013-10-31' , 2 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (141 , 196 , 55 , 425 , '2013-10-06' , 1 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (142 , 103 , 56 , 112 , '2013-10-04' , 1 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (143 , 2 , 56 , 427 , '2013-10-04' , 0 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (144 , 81 , 56 , 175 , '2013-11-01' , 0 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (145 , 136 , 57 , 53 , '2013-10-21' , 1 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (146 , 29 , 57 , 276 , '2013-10-03' , 1 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (147 , 193 , 58 , 382 , '2013-10-27' , 4 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (148 , 59 , 59 , 354 , '2013-11-16' , 0 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (149 , 82 , 59 , 113 , '2013-11-26' , 1 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (150 , 94 , 60 , 311 , '2013-12-08' , 1 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (151 , 36 , 60 , 195 , '2013-11-26' , 1 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (152 , 79 , 61 , 223 , '2013-12-01' , 0 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (153 , 50 , 61 , 150 , '2013-12-29' , 0 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (154 , 100 , 62 , 38 , '2013-12-03' , 1 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (155 , 246 , 62 , 407 , '2013-12-21' , 1 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (156 , 75 , 63 , 256 , '2013-12-19' , 1 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (157 , 250 , 63 , 125 , '2013-11-28' , 2 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (158 , 169 , 64 , 291 , '2013-11-30' , 1 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (159 , 88 , 64 , 310 , '2013-12-02' , 0 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (160 , 24 , 65 , 192 , '2014-01-28' , 0 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (161 , 100 , 65 , 14 , '2014-01-19' , 4 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (162 , 54 , 65 , 6 , '2014-01-06' , 0 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (163 , 182 , 65 , 177 , '2013-12-31' , 2 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (164 , 83 , 66 , 3 , '2014-01-19' , 2 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (165 , 80 , 66 , 438 , '2014-01-28' , 1 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (166 , 15 , 66 , 225 , '2014-01-31' , 0 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (167 , 57 , 66 , 235 , '2014-01-23' , 1 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (168 , 147 , 67 , 167 , '2014-01-24' , 3 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (169 , 27 , 67 , 19 , '2014-01-01' , 0 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (170 , 128 , 67 , 305 , '2014-01-30' , 0 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (171 , 134 , 68 , 368 , '2014-02-04' , 1 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (172 , 117 , 68 , 385 , '2014-01-15' , 0 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (173 , 47 , 69 , 39 , '2014-01-26' , 0 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (174 , 142 , 69 , 117 , '2014-02-03' , 1 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (175 , 18 , 70 , 223 , '2014-01-24' , 0 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (176 , 113 , 70 , 18 , '2014-02-13' , 1 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (177 , 106 , 71 , 304 , '2014-02-06' , 0 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (178 , 101 , 71 , 337 , '2014-02-14' , 0 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (179 , 117 , 72 , 5 , '2014-02-14' , 1 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (180 , 232 , 72 , 240 , '2014-03-08' , 1 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (181 , 5 , 73 , 221 , '2014-02-17' , 0 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (182 , 229 , 73 , 164 , '2014-02-18' , 2 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (183 , 164 , 74 , 319 , '2014-02-13' , 2 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (184 , 87 , 74 , 274 , '2014-03-06' , 0 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (185 , 28 , 75 , 183 , '2014-03-10' , 0 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (186 , 5 , 75 , 210 , '2014-03-23' , 0 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (187 , 24 , 75 , 447 , '2014-03-03' , 0 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (188 , 59 , 75 , 359 , '2014-03-13' , 0 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (189 , 17 , 76 , 99 , '2014-03-16' , 1 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (190 , 111 , 76 , 6 , '2014-03-29' , 1 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (191 , 74 , 77 , 1 , '2014-03-11' , 0 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (192 , 91 , 77 , 4 , '2014-03-01' , 5 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (193 , 169 , 78 , 307 , '2014-03-11' , 3 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (194 , 57 , 78 , 121 , '2014-04-03' , 2 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (195 , 176 , 79 , 463 , '2014-04-05' , 2 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (196 , 80 , 79 , 211 , '2014-04-10' , 0 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (197 , 31 , 80 , 433 , '2014-03-13' , 0 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (198 , 116 , 80 , 23 , '2014-03-29' , 1 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (199 , 92 , 81 , 375 , '2014-04-02' , 0 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (200 , 181 , 81 , 82 , '2014-03-24' , 4 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (201 , 38 , 82 , 22 , '2014-03-29' , 0 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (202 , 27 , 82 , 290 , '2014-03-18' , 1 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (203 , 55 , 82 , 211 , '2014-04-04' , 1 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (204 , 4 , 83 , 156 , '2014-04-12' , 0 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (205 , 70 , 83 , 29 , '2014-04-21' , 2 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (206 , 104 , 83 , 406 , '2014-04-22' , 3 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (207 , 115 , 84 , 11 , '2014-05-02' , 1 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (208 , 32 , 85 , 134 , '2014-05-14' , 1 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (209 , 121 , 85 , 349 , '2014-04-13' , 0 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (210 , 71 , 85 , 372 , '2014-05-03' , 1 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (211 , 189 , 85 , 268 , '2014-05-02' , 0 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (212 , 87 , 86 , 319 , '2014-04-19' , 1 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (213 , 46 , 86 , 417 , '2014-04-19' , 1 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (214 , 6 , 86 , 461 , '2014-04-23' , 0 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (215 , 131 , 86 , 197 , '2014-05-09' , 0 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (216 , 14 , 87 , 412 , '2014-04-30' , 0 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (217 , 120 , 87 , 8 , '2014-05-08' , 0 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (218 , 144 , 87 , 423 , '2014-05-09' , 1 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (219 , 101 , 88 , 202 , '2014-05-04' , 2 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (220 , 31 , 88 , 105 , '2014-04-14' , 1 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (221 , 67 , 88 , 258 , '2014-04-12' , 0 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (222 , 196 , 88 , 269 , '2014-04-17' , 1 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (223 , 136 , 89 , 454 , '2014-05-09' , 3 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (224 , 187 , 89 , 1 , '2014-05-13' , 3 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (225 , 21 , 90 , 96 , '2014-06-04' , 0 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (226 , 135 , 90 , 103 , '2014-06-14' , 0 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (227 , 79 , 91 , 323 , '2014-06-02' , 0 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (228 , 92 , 91 , 115 , '2014-05-22' , 0 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (229 , 62 , 91 , 99 , '2014-06-23' , 1 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (230 , 159 , 92 , 118 , '2014-07-04' , 2 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (231 , 113 , 92 , 314 , '2014-07-07' , 1 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (232 , 151 , 93 , 277 , '2014-06-21' , 1 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (233 , 119 , 93 , 41 , '2014-07-14' , 1 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (234 , 77 , 94 , 24 , '2014-07-15' , 0 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (235 , 48 , 94 , 395 , '2014-07-05' , 0 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (236 , 13 , 94 , 167 , '2014-07-13' , 0 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (237 , 66 , 94 , 250 , '2014-06-15' , 0 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (238 , 55 , 95 , 198 , '2014-07-03' , 1 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (239 , 65 , 95 , 163 , '2014-06-22' , 0 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (240 , 41 , 95 , 222 , '2014-06-29' , 0 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (241 , 25 , 96 , 412 , '2014-06-30' , 0 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (242 , 152 , 96 , 138 , '2014-07-09' , 1 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (243 , 74 , 96 , 279 , '2014-07-04' , 2 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (244 , 84 , 97 , 470 , '2014-07-26' , 0 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (245 , 109 , 97 , 198 , '2014-08-09' , 2 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (246 , 74 , 98 , 361 , '2014-08-01' , 1 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (247 , 102 , 98 , 433 , '2014-08-01' , 2 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (248 , 92 , 99 , 32 , '2014-08-09' , 0 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (249 , 164 , 99 , 472 , '2014-08-01' , 2 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (250 , 172 , 100 , 3 , '2014-07-20' , 2 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (251 , 89 , 100 , 206 , '2014-08-09' , 0 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (252 , 20 , 101 , 425 , '2014-07-24' , 0 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (253 , 86 , 101 , 463 , '2014-08-07' , 3 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (254 , 76 , 101 , 352 , '2014-08-14' , 1 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (255 , 83 , 102 , 96 , '2014-09-07' , 1 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (256 , 37 , 102 , 271 , '2014-08-11' , 0 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (257 , 130 , 103 , 463 , '2014-08-22' , 2 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (258 , 179 , 103 , 32 , '2014-08-11' , 0 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (259 , 122 , 104 , 104 , '2014-08-29' , 0 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (260 , 74 , 104 , 442 , '2014-09-05' , 1 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (261 , 67 , 105 , 75 , '2014-09-02' , 1 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (262 , 109 , 105 , 334 , '2014-08-12' , 2 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (263 , 153 , 105 , 125 , '2014-08-12' , 2 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (264 , 45 , 106 , 132 , '2014-09-18' , 1 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (265 , 64 , 106 , 239 , '2014-09-12' , 2 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (266 , 90 , 106 , 202 , '2014-09-02' , 2 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (267 , 177 , 107 , 406 , '2014-09-24' , 3 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (268 , 75 , 107 , 292 , '2014-09-28' , 1 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (269 , 8 , 108 , 208 , '2014-10-28' , 0 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (270 , 28 , 108 , 442 , '2014-10-18' , 0 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (271 , 83 , 108 , 287 , '2014-10-09' , 0 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (272 , 56 , 109 , 342 , '2014-10-28' , 0 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (273 , 32 , 109 , 117 , '2014-10-06' , 1 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (274 , 81 , 109 , 444 , '2014-10-21' , 0 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (275 , 51 , 110 , 156 , '2014-10-01' , 1 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (276 , 106 , 110 , 86 , '2014-09-29' , 2 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (277 , 19 , 111 , 429 , '2014-10-19' , 1 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (278 , 222 , 111 , 102 , '2014-11-11' , 1 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (279 , 135 , 112 , 373 , '2014-10-18' , 3 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (280 , 47 , 112 , 265 , '2014-10-28' , 1 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (281 , 37 , 113 , 375 , '2014-11-12' , 0 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (282 , 59 , 113 , 311 , '2014-11-17' , 0 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (283 , 20 , 113 , 195 , '2014-10-18' , 0 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (284 , 27 , 114 , 97 , '2014-11-20' , 0 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (285 , 25 , 114 , 450 , '2014-10-29' , 0 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (286 , 116 , 114 , 155 , '2014-11-16' , 0 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (287 , 142 , 115 , 413 , '2014-12-08' , 1 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (288 , 2 , 115 , 364 , '2014-11-26' , 0 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (289 , 48 , 115 , 208 , '2014-11-24' , 0 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (290 , 13 , 116 , 75 , '2014-12-12' , 0 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (291 , 135 , 116 , 421 , '2014-12-02' , 1 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (292 , 50 , 116 , 247 , '2014-11-19' , 0 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (293 , 17 , 117 , 389 , '2014-12-22' , 0 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (294 , 114 , 117 , 334 , '2014-12-17' , 0 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (295 , 113 , 117 , 75 , '2014-12-10' , 1 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (296 , 24 , 118 , 451 , '2014-12-16' , 0 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (297 , 100 , 118 , 342 , '2014-12-31' , 2 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (298 , 72 , 118 , 429 , '2014-12-07' , 1 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (299 , 147 , 119 , 218 , '2014-12-25' , 3 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (300 , 154 , 119 , 261 , '2014-12-20' , 0 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (301 , 156 , 120 , 464 , '2014-12-25' , 2 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (302 , 196 , 120 , 202 , '2015-01-09' , 0 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (303 , 208 , 121 , 141 , '2015-01-12' , 2 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (304 , 198 , 121 , 148 , '2015-01-11' , 2 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (305 , 17 , 122 , 288 , '2015-01-04' , 0 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (306 , 109 , 122 , 40 , '2015-01-01' , 1 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (307 , 74 , 122 , 372 , '2014-12-26' , 1 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (308 , 127 , 123 , 107 , '2015-01-02' , 2 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (309 , 29 , 123 , 85 , '2015-01-08' , 0 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (310 , 46 , 124 , 171 , '2015-01-06' , 0 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (311 , 133 , 124 , 199 , '2015-01-18' , 3 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (312 , 177 , 124 , 429 , '2015-01-26' , 2 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (313 , 48 , 125 , 98 , '2015-01-22' , 1 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (314 , 101 , 125 , 366 , '2015-01-19' , 2 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (315 , 1 , 125 , 130 , '2015-01-27' , 0 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (316 , 79 , 125 , 347 , '2015-02-02' , 0 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (317 , 117 , 126 , 447 , '2015-02-08' , 2 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (318 , 92 , 127 , 103 , '2015-03-02' , 3 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (319 , 132 , 127 , 281 , '2015-03-02' , 3 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (320 , 161 , 128 , 286 , '2015-02-20' , 4 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (321 , 152 , 128 , 5 , '2015-02-04' , 0 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (322 , 137 , 129 , 370 , '2015-02-07' , 2 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (323 , 94 , 129 , 21 , '2015-02-16' , 0 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (324 , 91 , 130 , 440 , '2015-02-25' , 0 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (325 , 202 , 130 , 406 , '2015-03-06' , 0 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (326 , 119 , 131 , 327 , '2015-02-26' , 1 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (327 , 83 , 131 , 303 , '2015-02-11' , 3 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (328 , 53 , 132 , 137 , '2015-03-25' , 0 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (329 , 4 , 132 , 340 , '2015-03-06' , 0 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (330 , 51 , 132 , 322 , '2015-03-25' , 0 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (331 , 28 , 132 , 142 , '2015-03-21' , 0 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (332 , 54 , 133 , 219 , '2015-03-21' , 0 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (333 , 188 , 133 , 185 , '2015-04-08' , 1 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (334 , 29 , 134 , 138 , '2015-03-29' , 0 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (335 , 139 , 134 , 425 , '2015-03-29' , 2 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (336 , 44 , 135 , 254 , '2015-04-03' , 0 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (337 , 30 , 135 , 155 , '2015-04-10' , 0 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (338 , 79 , 135 , 139 , '2015-04-11' , 1 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (339 , 66 , 136 , 308 , '2015-04-15' , 1 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (340 , 83 , 136 , 390 , '2015-04-14' , 1 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (341 , 57 , 136 , 35 , '2015-04-13' , 0 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (342 , 226 , 136 , 31 , '2015-03-21' , 1 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (343 , 59 , 137 , 152 , '2015-04-23' , 0 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (344 , 27 , 137 , 469 , '2015-04-30' , 0 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (345 , 61 , 137 , 1 , '2015-04-26' , 2 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (346 , 19 , 137 , 156 , '2015-03-29' , 0 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (347 , 139 , 137 , 323 , '2015-04-27' , 0 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (348 , 165 , 138 , 378 , '2015-04-21' , 2 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (349 , 51 , 138 , 56 , '2015-05-16' , 1 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (350 , 112 , 139 , 3 , '2015-05-04' , 0 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (351 , 52 , 139 , 387 , '2015-05-12' , 2 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (352 , 50 , 140 , 459 , '2015-05-02' , 0 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (353 , 17 , 140 , 126 , '2015-05-05' , 2 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (354 , 144 , 140 , 356 , '2015-05-08' , 1 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (355 , 98 , 141 , 327 , '2015-06-07' , 2 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (356 , 146 , 141 , 302 , '2015-05-28' , 1 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (357 , 24 , 142 , 226 , '2015-06-11' , 0 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (358 , 171 , 142 , 170 , '2015-06-11' , 1 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (359 , 136 , 143 , 383 , '2015-06-03' , 3 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (360 , 148 , 143 , 355 , '2015-06-07' , 3 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (361 , 28 , 144 , 344 , '2015-05-28' , 0 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (362 , 154 , 144 , 106 , '2015-06-19' , 3 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (363 , 27 , 144 , 138 , '2015-06-16' , 3 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (364 , 48 , 145 , 364 , '2015-06-07' , 0 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (365 , 1 , 145 , 122 , '2015-06-21' , 0 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (366 , 34 , 145 , 225 , '2015-06-11' , 0 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (367 , 105 , 145 , 70 , '2015-06-14' , 1 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (368 , 22 , 146 , 92 , '2015-07-01' , 1 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (369 , 60 , 146 , 20 , '2015-06-20' , 0 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (370 , 188 , 146 , 160 , '2015-07-01' , 1 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (371 , 10 , 147 , 417 , '2015-06-28' , 0 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (372 , 105 , 147 , 408 , '2015-06-19' , 0 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (373 , 246 , 147 , 17 , '2015-06-08' , 3 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (374 , 77 , 148 , 151 , '2015-06-24' , 0 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (375 , 43 , 148 , 209 , '2015-07-02' , 1 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (376 , 25 , 148 , 468 , '2015-06-24' , 0 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (377 , 206 , 149 , 326 , '2015-07-01' , 6 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (378 , 179 , 149 , 365 , '2015-06-25' , 1 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (379 , 101 , 150 , 110 , '2015-06-09' , 1 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (380 , 98 , 150 , 358 , '2015-06-30' , 0 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (381 , 26 , 151 , 472 , '2015-07-10' , 1 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (382 , 9 , 151 , 212 , '2015-06-29' , 0 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (383 , 3 , 151 , 14 , '2015-07-25' , 0 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (384 , 54 , 151 , 123 , '2015-07-26' , 1 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (385 , 11 , 151 , 350 , '2015-07-09' , 0 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (386 , 19 , 151 , 296 , '2015-06-28' , 0 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (387 , 9 , 151 , 11 , '2015-07-08' , 1 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (388 , 146 , 151 , 83 , '2015-07-16' , 0 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (389 , 28 , 152 , 368 , '2015-06-28' , 0 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (390 , 69 , 152 , 296 , '2015-06-29' , 1 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (391 , 46 , 152 , 469 , '2015-07-08' , 0 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (392 , 32 , 153 , 462 , '2015-07-28' , 0 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (393 , 94 , 153 , 38 , '2015-07-26' , 2 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (394 , 123 , 153 , 420 , '2015-07-20' , 0 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (395 , 102 , 154 , 18 , '2015-07-22' , 0 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (396 , 83 , 154 , 110 , '2015-08-05' , 0 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (397 , 71 , 154 , 416 , '2015-08-12' , 1 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (398 , 84 , 155 , 469 , '2015-08-14' , 2 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (399 , 218 , 155 , 428 , '2015-08-11' , 1 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (400 , 177 , 156 , 130 , '2015-08-17' , 2 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (401 , 139 , 156 , 174 , '2015-08-05' , 2 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (402 , 91 , 157 , 168 , '2015-08-18' , 1 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (403 , 84 , 157 , 347 , '2015-08-21' , 2 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (404 , 112 , 158 , 371 , '2015-08-14' , 0 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (405 , 150 , 158 , 425 , '2015-08-31' , 1 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (406 , 194 , 159 , 318 , '2015-08-16' , 2 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (407 , 157 , 159 , 397 , '2015-08-27' , 1 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (408 , 110 , 160 , 209 , '2015-09-09' , 1 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (409 , 13 , 160 , 189 , '2015-09-25' , 1 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (410 , 85 , 160 , 296 , '2015-09-09' , 2 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (411 , 75 , 161 , 38 , '2015-09-21' , 1 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (412 , 135 , 161 , 239 , '2015-09-20' , 2 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (413 , 4 , 162 , 66 , '2015-09-26' , 0 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (414 , 115 , 162 , 409 , '2015-10-05' , 1 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (415 , 153 , 162 , 248 , '2015-09-29' , 5 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (416 , 54 , 163 , 384 , '2015-09-14' , 1 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (417 , 34 , 163 , 457 , '2015-09-23' , 0 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (418 , 60 , 163 , 285 , '2015-09-19' , 0 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (419 , 141 , 164 , 45 , '2015-10-03' , 1 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (420 , 5 , 165 , 128 , '2015-09-23' , 1 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (421 , 20 , 165 , 21 , '2015-10-16' , 0 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (422 , 86 , 165 , 407 , '2015-10-13' , 1 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (423 , 67 , 166 , 90 , '2015-09-28' , 2 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (424 , 60 , 166 , 380 , '2015-10-15' , 1 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (425 , 62 , 167 , 274 , '2015-10-02' , 0 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (426 , 145 , 167 , 282 , '2015-10-02' , 1 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (427 , 60 , 168 , 108 , '2015-09-29' , 0 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (428 , 35 , 168 , 344 , '2015-09-19' , 1 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (429 , 146 , 168 , 336 , '2015-09-17' , 1 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (430 , 82 , 169 , 368 , '2015-10-18' , 1 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (431 , 131 , 169 , 188 , '2015-10-20' , 3 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (432 , 42 , 170 , 425 , '2015-10-15' , 0 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (433 , 4 , 170 , 418 , '2015-11-13' , 0 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (434 , 44 , 170 , 473 , '2015-11-07' , 0 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (435 , 95 , 170 , 41 , '2015-10-27' , 3 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (436 , 27 , 171 , 197 , '2015-10-18' , 0 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (437 , 94 , 171 , 130 , '2015-10-31' , 2 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (438 , 85 , 172 , 113 , '2015-11-07' , 0 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (439 , 28 , 172 , 355 , '2015-10-22' , 0 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (440 , 75 , 172 , 35 , '2015-11-08' , 2 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (441 , 18 , 173 , 123 , '2015-11-11' , 0 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (442 , 110 , 173 , 272 , '2015-11-05' , 3 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (443 , 83 , 174 , 413 , '2015-11-25' , 1 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (444 , 245 , 174 , 191 , '2015-11-20' , 1 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (445 , 97 , 175 , 139 , '2015-11-02' , 1 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (446 , 113 , 175 , 97 , '2015-11-14' , 4 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (447 , 210 , 175 , 189 , '2015-10-31' , 4 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (448 , 101 , 176 , 157 , '2015-11-27' , 0 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (449 , 82 , 176 , 473 , '2015-11-08' , 0 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (450 , 104 , 177 , 102 , '2015-12-03' , 1 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (451 , 33 , 177 , 194 , '2015-12-05' , 0 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (452 , 115 , 178 , 328 , '2015-11-15' , 1 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (453 , 16 , 179 , 259 , '2015-11-21' , 0 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (454 , 195 , 179 , 402 , '2015-11-30' , 5 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (455 , 131 , 180 , 41 , '2015-12-24' , 4 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (456 , 45 , 180 , 445 , '2015-12-14' , 0 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (457 , 127 , 181 , 298 , '2016-01-07' , 0 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (458 , 13 , 181 , 216 , '2016-01-12' , 0 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (459 , 29 , 181 , 374 , '2016-01-09' , 1 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (460 , 107 , 181 , 294 , '2016-01-09' , 0 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (461 , 127 , 182 , 160 , '2015-12-28' , 3 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (462 , 24 , 182 , 303 , '2016-01-01' , 0 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (463 , 79 , 182 , 256 , '2016-01-06' , 0 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (464 , 208 , 182 , 399 , '2015-12-18' , 1 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (465 , 122 , 183 , 283 , '2015-12-24' , 3 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (466 , 30 , 183 , 358 , '2015-12-21' , 1 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (467 , 75 , 183 , 320 , '2016-01-06' , 0 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (468 , 176 , 183 , 438 , '2015-12-29' , 1 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (469 , 168 , 184 , 10 , '2016-01-25' , 3 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (470 , 182 , 184 , 319 , '2016-01-30' , 0 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (471 , 100 , 185 , 232 , '2016-01-10' , 0 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (472 , 31 , 185 , 358 , '2016-01-14' , 0 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (473 , 30 , 186 , 72 , '2016-01-12' , 0 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (474 , 187 , 186 , 357 , '2016-01-17' , 3 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (475 , 8 , 187 , 91 , '2016-01-15' , 0 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (476 , 116 , 187 , 17 , '2016-01-11' , 4 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (477 , 37 , 187 , 64 , '2016-02-01' , 0 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (478 , 22 , 187 , 135 , '2016-02-02' , 0 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (479 , 81 , 187 , 53 , '2016-01-20' , 0 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (480 , 87 , 188 , 258 , '2016-01-31' , 0 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (481 , 115 , 188 , 197 , '2016-01-12' , 1 )
