INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (1 , 119 , 1 , 362 , '2013-01-03' , 1 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (2 , 34 , 1 , 193 , '2013-01-03' , 0 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (3 , 21 , 2 , 345 , '2012-12-27' , 0 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (4 , 51 , 2 , 265 , '2013-01-01' , 0 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (5 , 62 , 2 , 64 , '2012-12-28' , 0 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (6 , 34 , 3 , 303 , '2013-01-10' , 0 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (7 , 118 , 3 , 304 , '2013-01-20' , 1 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (8 , 107 , 3 , 438 , '2013-01-20' , 1 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (9 , 108 , 4 , 67 , '2013-01-05' , 2 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (10 , 67 , 4 , 68 , '2012-12-26' , 0 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (11 , 51 , 4 , 339 , '2013-01-24' , 0 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (12 , 134 , 5 , 170 , '2013-01-25' , 0 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (13 , 221 , 5 , 182 , '2013-01-16' , 1 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (14 , 3 , 6 , 152 , '2013-02-02' , 0 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (15 , 110 , 6 , 155 , '2013-01-23' , 1 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (16 , 105 , 7 , 110 , '2013-01-31' , 1 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (17 , 183 , 7 , 428 , '2013-01-27' , 4 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (18 , 38 , 8 , 471 , '2013-02-17' , 1 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (19 , 6 , 8 , 191 , '2013-01-31' , 0 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (20 , 106 , 8 , 419 , '2013-02-03' , 3 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (21 , 148 , 9 , 145 , '2013-02-20' , 1 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (22 , 183 , 9 , 375 , '2013-02-06' , 4 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (23 , 50 , 10 , 174 , '2013-02-15' , 0 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (24 , 92 , 10 , 196 , '2013-02-21' , 3 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (25 , 54 , 11 , 20 , '2013-02-21' , 1 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (26 , 41 , 11 , 101 , '2013-01-24' , 0 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (27 , 7 , 11 , 321 , '2013-02-05' , 0 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (28 , 54 , 11 , 384 , '2013-02-18' , 1 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (29 , 176 , 12 , 114 , '2013-02-20' , 2 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (30 , 150 , 12 , 327 , '2013-02-09' , 3 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (31 , 135 , 13 , 280 , '2013-02-24' , 2 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (32 , 178 , 13 , 246 , '2013-02-14' , 1 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (33 , 239 , 14 , 278 , '2013-02-26' , 3 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (34 , 64 , 15 , 147 , '2013-03-27' , 0 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (35 , 24 , 15 , 111 , '2013-03-31' , 0 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (36 , 12 , 15 , 96 , '2013-03-31' , 0 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (37 , 37 , 15 , 326 , '2013-04-04' , 0 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (38 , 129 , 15 , 325 , '2013-03-16' , 1 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (39 , 47 , 16 , 263 , '2013-04-06' , 2 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (40 , 44 , 16 , 33 , '2013-03-17' , 0 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (41 , 58 , 16 , 333 , '2013-03-09' , 1 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (42 , 76 , 17 , 235 , '2013-04-04' , 0 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (43 , 99 , 17 , 446 , '2013-03-14' , 1 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (44 , 102 , 18 , 245 , '2013-03-25' , 0 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (45 , 54 , 18 , 448 , '2013-03-31' , 1 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (46 , 6 , 19 , 402 , '2013-04-13' , 0 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (47 , 56 , 19 , 6 , '2013-04-14' , 0 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (48 , 123 , 19 , 274 , '2013-03-28' , 1 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (49 , 25 , 20 , 306 , '2013-04-15' , 0 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (50 , 122 , 20 , 366 , '2013-03-20' , 1 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (51 , 20 , 20 , 69 , '2013-04-09' , 0 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (52 , 87 , 20 , 191 , '2013-04-05' , 0 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (53 , 12 , 21 , 168 , '2013-04-02' , 0 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (54 , 177 , 21 , 8 , '2013-04-14' , 6 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (55 , 148 , 22 , 347 , '2013-03-28' , 1 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (56 , 54 , 22 , 105 , '2013-04-16' , 0 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (57 , 186 , 22 , 205 , '2013-04-18' , 1 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (58 , 102 , 23 , 4 , '2013-03-28' , 0 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (59 , 28 , 23 , 132 , '2013-04-12' , 0 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (60 , 3 , 24 , 146 , '2013-04-18' , 0 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (61 , 8 , 24 , 391 , '2013-04-11' , 0 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (62 , 71 , 24 , 17 , '2013-04-08' , 1 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (63 , 44 , 24 , 166 , '2013-03-27' , 1 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (64 , 103 , 24 , 303 , '2013-04-17' , 1 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (65 , 3 , 25 , 314 , '2013-04-15' , 0 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (66 , 63 , 25 , 183 , '2013-04-17' , 0 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (67 , 35 , 25 , 404 , '2013-04-24' , 2 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (68 , 103 , 25 , 236 , '2013-04-28' , 0 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (69 , 23 , 26 , 178 , '2013-04-22' , 2 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (70 , 3 , 26 , 392 , '2013-04-09' , 0 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (71 , 96 , 26 , 471 , '2013-04-07' , 0 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (72 , 168 , 27 , 304 , '2013-05-03' , 3 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (73 , 25 , 27 , 445 , '2013-04-27' , 1 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (74 , 98 , 28 , 220 , '2013-06-04' , 1 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (75 , 6 , 28 , 152 , '2013-05-05' , 0 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (76 , 86 , 28 , 8 , '2013-05-20' , 1 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (77 , 65 , 29 , 88 , '2013-05-09' , 0 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (78 , 17 , 29 , 146 , '2013-06-02' , 0 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (79 , 109 , 29 , 137 , '2013-05-16' , 0 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (80 , 85 , 30 , 430 , '2013-06-05' , 1 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (81 , 4 , 30 , 192 , '2013-05-14' , 0 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (82 , 160 , 30 , 347 , '2013-06-04' , 2 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (83 , 23 , 31 , 313 , '2013-06-10' , 1 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (84 , 83 , 31 , 188 , '2013-06-07' , 1 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (85 , 61 , 31 , 346 , '2013-05-19' , 0 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (86 , 93 , 32 , 222 , '2013-05-16' , 0 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (87 , 15 , 32 , 323 , '2013-05-29' , 0 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (88 , 95 , 32 , 81 , '2013-05-25' , 0 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (89 , 73 , 33 , 372 , '2013-05-25' , 2 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (90 , 68 , 33 , 41 , '2013-05-28' , 0 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (91 , 97 , 34 , 455 , '2013-07-02' , 1 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (92 , 59 , 34 , 233 , '2013-06-02' , 0 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (93 , 56 , 35 , 141 , '2013-06-07' , 1 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (94 , 101 , 35 , 460 , '2013-06-23' , 1 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (95 , 104 , 35 , 457 , '2013-07-02' , 2 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (96 , 52 , 36 , 333 , '2013-06-27' , 0 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (97 , 71 , 36 , 272 , '2013-07-07' , 0 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (98 , 112 , 37 , 310 , '2013-07-06' , 0 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (99 , 2 , 37 , 231 , '2013-07-27' , 0 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (100 , 91 , 37 , 218 , '2013-07-24' , 0 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (101 , 65 , 38 , 384 , '2013-07-24' , 1 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (102 , 42 , 38 , 331 , '2013-07-05' , 0 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (103 , 77 , 38 , 229 , '2013-07-20' , 1 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (104 , 59 , 39 , 419 , '2013-07-26' , 0 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (105 , 56 , 39 , 101 , '2013-08-05' , 0 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (106 , 52 , 40 , 323 , '2013-08-05' , 0 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (107 , 103 , 40 , 76 , '2013-08-01' , 1 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (108 , 46 , 41 , 39 , '2013-07-30' , 1 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (109 , 132 , 41 , 333 , '2013-07-10' , 1 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (110 , 96 , 42 , 253 , '2013-07-09' , 2 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (111 , 247 , 42 , 65 , '2013-07-13' , 2 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (112 , 36 , 43 , 261 , '2013-07-17' , 0 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (113 , 67 , 43 , 255 , '2013-07-31' , 0 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (114 , 95 , 43 , 163 , '2013-07-31' , 0 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (115 , 44 , 44 , 68 , '2013-08-03' , 1 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (116 , 68 , 44 , 264 , '2013-07-27' , 1 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (117 , 143 , 44 , 65 , '2013-07-30' , 0 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (118 , 51 , 45 , 144 , '2013-09-04' , 0 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (119 , 92 , 45 , 21 , '2013-08-24' , 1 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (120 , 85 , 46 , 64 , '2013-08-21' , 1 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (121 , 58 , 46 , 107 , '2013-09-03' , 0 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (122 , 82 , 47 , 318 , '2013-09-04' , 0 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (123 , 148 , 47 , 159 , '2013-08-19' , 1 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (124 , 139 , 48 , 98 , '2013-08-30' , 3 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (125 , 75 , 48 , 408 , '2013-09-05' , 2 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (126 , 52 , 49 , 105 , '2013-08-27' , 2 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (127 , 169 , 49 , 144 , '2013-09-03' , 3 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (128 , 104 , 49 , 190 , '2013-09-09' , 1 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (129 , 37 , 50 , 49 , '2013-09-13' , 0 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (130 , 81 , 50 , 222 , '2013-09-12' , 0 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (131 , 74 , 51 , 7 , '2013-10-08' , 1 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (132 , 25 , 51 , 254 , '2013-10-11' , 1 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (133 , 40 , 51 , 378 , '2013-10-01' , 2 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (134 , 131 , 51 , 49 , '2013-10-03' , 0 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (135 , 119 , 52 , 201 , '2013-10-20' , 1 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (136 , 101 , 53 , 152 , '2013-10-13' , 3 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (137 , 2 , 53 , 101 , '2013-10-02' , 0 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (138 , 18 , 53 , 371 , '2013-10-17' , 0 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (139 , 72 , 54 , 241 , '2013-10-22' , 0 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (140 , 84 , 54 , 423 , '2013-09-26' , 0 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (141 , 100 , 55 , 199 , '2013-10-22' , 0 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (142 , 82 , 55 , 45 , '2013-10-18' , 2 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (143 , 164 , 55 , 170 , '2013-11-03' , 3 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (144 , 45 , 56 , 210 , '2013-10-19' , 0 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (145 , 39 , 56 , 396 , '2013-10-30' , 0 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (146 , 90 , 56 , 199 , '2013-10-30' , 0 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (147 , 82 , 56 , 233 , '2013-10-17' , 0 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (148 , 29 , 57 , 69 , '2013-10-29' , 0 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (149 , 3 , 57 , 182 , '2013-11-18' , 0 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (150 , 74 , 57 , 322 , '2013-11-11' , 0 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (151 , 50 , 57 , 355 , '2013-11-01' , 1 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (152 , 114 , 58 , 215 , '2013-11-02' , 1 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (153 , 83 , 59 , 298 , '2013-11-27' , 2 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (154 , 74 , 59 , 104 , '2013-11-01' , 0 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (155 , 123 , 60 , 300 , '2013-11-09' , 1 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (156 , 92 , 60 , 244 , '2013-11-19' , 1 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (157 , 119 , 61 , 210 , '2013-12-15' , 1 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (158 , 23 , 61 , 132 , '2013-12-02' , 0 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (159 , 6 , 62 , 273 , '2013-11-21' , 0 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (160 , 118 , 62 , 101 , '2013-12-01' , 0 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (161 , 41 , 63 , 170 , '2013-12-03' , 0 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (162 , 133 , 63 , 263 , '2013-12-11' , 0 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (163 , 145 , 64 , 19 , '2013-12-15' , 1 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (164 , 11 , 65 , 9 , '2013-12-20' , 0 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (165 , 126 , 65 , 178 , '2013-12-10' , 2 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (166 , 82 , 65 , 441 , '2013-12-04' , 1 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (167 , 229 , 66 , 467 , '2013-12-05' , 2 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (168 , 219 , 66 , 442 , '2013-12-02' , 0 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (169 , 40 , 67 , 312 , '2013-12-16' , 1 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (170 , 148 , 67 , 109 , '2013-12-05' , 0 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (171 , 166 , 67 , 461 , '2013-12-02' , 2 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (172 , 18 , 68 , 435 , '2013-12-13' , 0 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (173 , 108 , 68 , 66 , '2013-12-22' , 3 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (174 , 36 , 68 , 50 , '2013-12-09' , 0 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (175 , 51 , 69 , 471 , '2014-01-06' , 1 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (176 , 193 , 69 , 458 , '2013-12-24' , 3 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (177 , 71 , 70 , 110 , '2013-12-30' , 1 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (178 , 56 , 70 , 394 , '2014-01-10' , 1 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (179 , 227 , 71 , 136 , '2014-01-18' , 2 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (180 , 29 , 71 , 17 , '2014-01-31' , 0 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (181 , 92 , 72 , 231 , '2014-01-29' , 1 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (182 , 180 , 72 , 301 , '2014-01-28' , 0 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (183 , 152 , 73 , 264 , '2014-02-11' , 4 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (184 , 39 , 73 , 360 , '2014-01-27' , 0 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (185 , 134 , 74 , 102 , '2014-02-01' , 2 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (186 , 125 , 74 , 77 , '2014-02-21' , 1 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (187 , 54 , 75 , 253 , '2014-02-20' , 1 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (188 , 40 , 75 , 320 , '2014-02-12' , 3 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (189 , 25 , 75 , 401 , '2014-02-13' , 1 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (190 , 104 , 76 , 307 , '2014-02-05' , 1 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (191 , 132 , 76 , 182 , '2014-02-27' , 0 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (192 , 83 , 77 , 112 , '2014-02-17' , 2 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (193 , 202 , 77 , 126 , '2014-02-26' , 1 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (194 , 90 , 78 , 304 , '2014-02-12' , 0 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (195 , 44 , 78 , 55 , '2014-02-25' , 0 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (196 , 11 , 79 , 291 , '2014-02-11' , 0 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (197 , 144 , 79 , 408 , '2014-02-27' , 1 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (198 , 199 , 80 , 218 , '2014-03-12' , 4 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (199 , 174 , 80 , 99 , '2014-03-08' , 3 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (200 , 27 , 81 , 353 , '2014-03-29' , 0 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (201 , 151 , 81 , 110 , '2014-03-24' , 1 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (202 , 218 , 81 , 283 , '2014-03-22' , 2 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (203 , 117 , 82 , 32 , '2014-03-08' , 1 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (204 , 140 , 82 , 345 , '2014-03-30' , 2 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (205 , 163 , 83 , 115 , '2014-03-28' , 2 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (206 , 149 , 83 , 363 , '2014-03-09' , 1 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (207 , 41 , 84 , 424 , '2014-04-11' , 0 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (208 , 91 , 84 , 147 , '2014-03-23' , 3 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (209 , 100 , 85 , 274 , '2014-04-20' , 1 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (210 , 57 , 85 , 340 , '2014-05-06' , 1 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (211 , 191 , 85 , 91 , '2014-05-04' , 2 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (212 , 154 , 86 , 393 , '2014-04-28' , 1 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (213 , 38 , 86 , 436 , '2014-04-26' , 0 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (214 , 113 , 86 , 373 , '2014-04-16' , 4 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (215 , 93 , 87 , 448 , '2014-04-21' , 0 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (216 , 127 , 87 , 241 , '2014-05-14' , 3 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (217 , 198 , 88 , 96 , '2014-04-22' , 2 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (218 , 4 , 88 , 193 , '2014-04-19' , 0 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (219 , 9 , 88 , 268 , '2014-05-18' , 0 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (220 , 10 , 88 , 233 , '2014-05-02' , 0 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (221 , 167 , 88 , 53 , '2014-05-13' , 4 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (222 , 112 , 89 , 276 , '2014-04-25' , 1 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (223 , 76 , 90 , 267 , '2014-04-20' , 0 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (224 , 108 , 90 , 303 , '2014-05-02' , 4 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (225 , 79 , 91 , 458 , '2014-05-14' , 1 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (226 , 117 , 91 , 423 , '2014-06-04' , 1 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (227 , 115 , 92 , 29 , '2014-05-06' , 2 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (228 , 116 , 92 , 387 , '2014-05-07' , 0 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (229 , 155 , 93 , 281 , '2014-05-27' , 0 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (230 , 122 , 93 , 467 , '2014-05-11' , 0 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (231 , 21 , 94 , 454 , '2014-05-27' , 0 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (232 , 131 , 94 , 240 , '2014-05-10' , 1 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (233 , 135 , 94 , 351 , '2014-05-21' , 0 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (234 , 98 , 95 , 349 , '2014-05-16' , 0 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (235 , 82 , 95 , 15 , '2014-05-24' , 1 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (236 , 200 , 95 , 336 , '2014-06-13' , 2 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (237 , 196 , 96 , 411 , '2014-06-03' , 3 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (238 , 20 , 97 , 9 , '2014-07-09' , 0 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (239 , 69 , 97 , 210 , '2014-07-18' , 1 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (240 , 6 , 97 , 438 , '2014-07-18' , 0 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (241 , 49 , 97 , 444 , '2014-07-02' , 0 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (242 , 38 , 98 , 256 , '2014-06-29' , 0 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (243 , 155 , 98 , 297 , '2014-06-25' , 2 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (244 , 68 , 99 , 15 , '2014-07-09' , 0 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (245 , 49 , 99 , 17 , '2014-07-14' , 0 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (246 , 154 , 99 , 398 , '2014-06-28' , 1 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (247 , 55 , 100 , 469 , '2014-07-15' , 1 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (248 , 48 , 100 , 239 , '2014-06-25' , 0 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (249 , 89 , 100 , 86 , '2014-07-13' , 2 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (250 , 95 , 101 , 349 , '2014-07-15' , 2 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (251 , 67 , 101 , 96 , '2014-07-26' , 0 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (252 , 19 , 102 , 184 , '2014-07-18' , 0 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (253 , 95 , 102 , 119 , '2014-08-12' , 2 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (254 , 139 , 102 , 219 , '2014-07-26' , 3 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (255 , 58 , 103 , 467 , '2014-08-01' , 0 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (256 , 153 , 103 , 243 , '2014-08-26' , 1 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (257 , 71 , 104 , 96 , '2014-08-21' , 0 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (258 , 62 , 104 , 172 , '2014-08-02' , 1 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (259 , 68 , 105 , 234 , '2014-08-25' , 4 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (260 , 57 , 105 , 127 , '2014-08-18' , 0 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (261 , 42 , 105 , 305 , '2014-09-06' , 1 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (262 , 70 , 106 , 149 , '2014-08-29' , 0 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (263 , 193 , 106 , 262 , '2014-08-15' , 1 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (264 , 10 , 107 , 17 , '2014-08-09' , 0 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (265 , 102 , 107 , 450 , '2014-08-14' , 2 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (266 , 151 , 108 , 96 , '2014-09-25' , 0 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (267 , 91 , 108 , 17 , '2014-09-25' , 1 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (268 , 86 , 109 , 133 , '2014-09-28' , 0 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (269 , 93 , 109 , 4 , '2014-09-25' , 1 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (270 , 236 , 109 , 46 , '2014-08-31' , 2 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (271 , 216 , 110 , 183 , '2014-09-19' , 2 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (272 , 41 , 110 , 441 , '2014-09-23' , 1 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (273 , 91 , 111 , 374 , '2014-10-26' , 0 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (274 , 89 , 111 , 403 , '2014-10-08' , 2 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (275 , 48 , 112 , 408 , '2014-10-06' , 0 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (276 , 228 , 112 , 67 , '2014-10-19' , 2 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (277 , 50 , 113 , 180 , '2014-10-17' , 0 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (278 , 109 , 113 , 218 , '2014-10-11' , 1 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (279 , 41 , 114 , 19 , '2014-10-27' , 1 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (280 , 250 , 114 , 349 , '2014-10-28' , 0 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (281 , 190 , 115 , 5 , '2014-10-27' , 0 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (282 , 195 , 116 , 250 , '2014-10-24' , 0 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (283 , 89 , 117 , 30 , '2014-11-03' , 1 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (284 , 156 , 117 , 332 , '2014-10-29' , 4 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (285 , 22 , 118 , 386 , '2014-11-19' , 0 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (286 , 131 , 118 , 44 , '2014-11-29' , 2 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (287 , 151 , 119 , 291 , '2014-12-08' , 1 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (288 , 178 , 119 , 197 , '2014-11-17' , 3 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (289 , 37 , 120 , 172 , '2014-12-13' , 0 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (290 , 37 , 120 , 273 , '2014-12-17' , 0 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (291 , 125 , 120 , 75 , '2014-12-05' , 1 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (292 , 93 , 121 , 435 , '2014-12-17' , 2 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (293 , 67 , 121 , 46 , '2014-12-12' , 0 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (294 , 96 , 122 , 21 , '2014-12-18' , 1 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (295 , 210 , 122 , 188 , '2014-12-18' , 1 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (296 , 68 , 123 , 3 , '2014-12-16' , 1 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (297 , 90 , 123 , 271 , '2014-12-04' , 0 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (298 , 106 , 124 , 101 , '2014-12-25' , 1 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (299 , 159 , 124 , 471 , '2015-01-04' , 3 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (300 , 47 , 125 , 343 , '2015-01-06' , 0 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (301 , 116 , 125 , 384 , '2014-12-26' , 1 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (302 , 61 , 126 , 123 , '2015-01-11' , 2 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (303 , 49 , 126 , 102 , '2015-01-22' , 2 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (304 , 13 , 126 , 463 , '2015-01-07' , 0 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (305 , 5 , 126 , 72 , '2014-12-30' , 0 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (306 , 37 , 126 , 240 , '2015-01-17' , 0 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (307 , 64 , 127 , 362 , '2014-12-30' , 0 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (308 , 56 , 127 , 87 , '2015-01-20' , 1 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (309 , 139 , 128 , 239 , '2015-01-21' , 0 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (310 , 50 , 129 , 33 , '2015-02-02' , 0 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (311 , 7 , 129 , 297 , '2015-01-25' , 0 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (312 , 58 , 129 , 88 , '2015-01-10' , 0 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (313 , 28 , 129 , 376 , '2015-01-14' , 0 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (314 , 120 , 130 , 433 , '2015-02-18' , 0 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (315 , 81 , 131 , 76 , '2015-03-03' , 0 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (316 , 152 , 131 , 198 , '2015-03-07' , 1 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (317 , 131 , 132 , 109 , '2015-03-08' , 2 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (318 , 134 , 132 , 62 , '2015-03-01' , 2 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (319 , 185 , 133 , 236 , '2015-02-05' , 4 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (320 , 111 , 134 , 38 , '2015-02-10' , 0 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (321 , 101 , 134 , 323 , '2015-02-25' , 2 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (322 , 85 , 135 , 28 , '2015-03-30' , 1 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (323 , 37 , 135 , 385 , '2015-03-06' , 1 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (324 , 88 , 135 , 328 , '2015-03-03' , 2 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (325 , 109 , 135 , 414 , '2015-03-09' , 0 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (326 , 69 , 136 , 363 , '2015-03-20' , 0 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (327 , 66 , 136 , 315 , '2015-03-10' , 0 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (328 , 145 , 136 , 340 , '2015-03-16' , 3 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (329 , 60 , 137 , 382 , '2015-04-09' , 3 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (330 , 134 , 137 , 131 , '2015-03-29' , 2 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (331 , 88 , 137 , 164 , '2015-04-03' , 0 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (332 , 26 , 138 , 423 , '2015-03-25' , 0 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (333 , 65 , 138 , 13 , '2015-04-19' , 1 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (334 , 122 , 138 , 190 , '2015-04-21' , 2 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (335 , 121 , 139 , 61 , '2015-04-12' , 1 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (336 , 6 , 139 , 470 , '2015-04-14' , 0 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (337 , 1 , 139 , 292 , '2015-04-12' , 0 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (338 , 83 , 139 , 379 , '2015-04-15' , 2 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (339 , 236 , 140 , 210 , '2015-04-22' , 3 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (340 , 77 , 141 , 446 , '2015-04-16' , 0 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (341 , 177 , 141 , 136 , '2015-04-29' , 2 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (342 , 130 , 142 , 96 , '2015-04-16' , 1 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (343 , 99 , 142 , 217 , '2015-04-05' , 0 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (344 , 60 , 143 , 9 , '2015-04-30' , 0 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (345 , 45 , 143 , 268 , '2015-05-03' , 0 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (346 , 9 , 143 , 453 , '2015-04-30' , 0 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (347 , 153 , 143 , 357 , '2015-04-19' , 1 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (348 , 29 , 144 , 432 , '2015-05-19' , 0 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (349 , 20 , 144 , 361 , '2015-04-28' , 2 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (350 , 70 , 144 , 376 , '2015-04-22' , 0 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (351 , 193 , 144 , 12 , '2015-04-25' , 1 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (352 , 88 , 145 , 262 , '2015-05-24' , 1 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (353 , 134 , 145 , 109 , '2015-05-16' , 2 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (354 , 52 , 145 , 327 , '2015-06-02' , 2 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (355 , 239 , 146 , 351 , '2015-05-19' , 2 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (356 , 36 , 147 , 97 , '2015-05-24' , 1 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (357 , 116 , 147 , 231 , '2015-05-24' , 1 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (358 , 149 , 148 , 327 , '2015-06-28' , 2 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (359 , 141 , 148 , 9 , '2015-06-03' , 0 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (360 , 104 , 149 , 419 , '2015-07-02' , 3 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (361 , 38 , 149 , 113 , '2015-07-12' , 0 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (362 , 30 , 150 , 81 , '2015-07-15' , 0 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (363 , 7 , 150 , 36 , '2015-07-20' , 0 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (364 , 67 , 150 , 50 , '2015-07-22' , 2 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (365 , 110 , 150 , 305 , '2015-07-03' , 0 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (366 , 191 , 151 , 294 , '2015-07-12' , 1 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (367 , 98 , 152 , 216 , '2015-07-19' , 0 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (368 , 36 , 152 , 407 , '2015-07-31' , 0 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (369 , 1 , 152 , 308 , '2015-07-27' , 0 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (370 , 13 , 152 , 96 , '2015-07-18' , 0 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (371 , 194 , 153 , 312 , '2015-07-08' , 1 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (372 , 53 , 154 , 183 , '2015-07-23' , 0 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (373 , 109 , 154 , 17 , '2015-07-09' , 2 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (374 , 191 , 155 , 145 , '2015-07-31' , 1 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (375 , 110 , 156 , 417 , '2015-07-22' , 2 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (376 , 98 , 156 , 366 , '2015-07-21' , 2 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (377 , 139 , 157 , 346 , '2015-08-05' , 1 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (378 , 14 , 158 , 395 , '2015-07-20' , 1 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (379 , 8 , 158 , 463 , '2015-08-07' , 0 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (380 , 133 , 158 , 422 , '2015-07-14' , 1 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (381 , 110 , 159 , 469 , '2015-08-12' , 1 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (382 , 31 , 159 , 303 , '2015-09-03' , 0 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (383 , 65 , 160 , 165 , '2015-08-29' , 1 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (384 , 80 , 160 , 126 , '2015-08-31' , 0 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (385 , 26 , 161 , 299 , '2015-08-30' , 0 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (386 , 39 , 161 , 362 , '2015-08-21' , 0 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (387 , 75 , 161 , 442 , '2015-08-20' , 1 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (388 , 77 , 162 , 47 , '2015-09-05' , 1 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (389 , 71 , 162 , 327 , '2015-09-14' , 0 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (390 , 97 , 163 , 19 , '2015-08-23' , 1 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (391 , 142 , 163 , 398 , '2015-09-06' , 0 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (392 , 87 , 164 , 30 , '2015-09-21' , 0 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (393 , 94 , 164 , 270 , '2015-09-26' , 3 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (394 , 114 , 165 , 325 , '2015-09-24' , 1 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (395 , 6 , 166 , 339 , '2015-09-12' , 0 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (396 , 14 , 166 , 61 , '2015-09-22' , 0 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (397 , 120 , 166 , 413 , '2015-09-29' , 3 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (398 , 199 , 166 , 236 , '2015-09-11' , 1 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (399 , 137 , 167 , 50 , '2015-09-29' , 1 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (400 , 112 , 167 , 344 , '2015-10-14' , 0 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (401 , 30 , 168 , 113 , '2015-10-31' , 0 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (402 , 66 , 168 , 252 , '2015-10-24' , 0 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (403 , 8 , 168 , 168 , '2015-10-19' , 1 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (404 , 76 , 168 , 342 , '2015-10-02' , 0 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (405 , 59 , 169 , 311 , '2015-10-10' , 0 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (406 , 49 , 169 , 3 , '2015-10-07' , 0 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (407 , 11 , 169 , 22 , '2015-10-14' , 1 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (408 , 174 , 170 , 363 , '2015-10-04' , 3 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (409 , 24 , 170 , 172 , '2015-11-02' , 0 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (410 , 78 , 170 , 325 , '2015-10-11' , 1 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (411 , 11 , 171 , 330 , '2015-10-20' , 0 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (412 , 75 , 171 , 33 , '2015-10-11' , 0 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (413 , 26 , 171 , 371 , '2015-11-05' , 0 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (414 , 119 , 171 , 211 , '2015-10-17' , 1 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (415 , 194 , 172 , 2 , '2015-10-22' , 4 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (416 , 180 , 173 , 24 , '2015-11-05' , 3 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (417 , 89 , 173 , 438 , '2015-10-31' , 0 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (418 , 16 , 174 , 407 , '2015-11-28' , 0 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (419 , 11 , 174 , 360 , '2015-12-14' , 0 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (420 , 88 , 174 , 408 , '2015-12-14' , 2 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (421 , 83 , 175 , 26 , '2015-12-02' , 0 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (422 , 89 , 175 , 308 , '2015-12-01' , 0 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (423 , 65 , 176 , 115 , '2015-11-22' , 2 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (424 , 78 , 176 , 392 , '2015-12-10' , 0 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (425 , 26 , 177 , 176 , '2015-12-02' , 0 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (426 , 158 , 177 , 261 , '2015-11-27' , 1 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (427 , 151 , 177 , 370 , '2015-11-24' , 2 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (428 , 183 , 178 , 287 , '2015-12-31' , 3 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (429 , 121 , 178 , 170 , '2015-12-22' , 1 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (430 , 176 , 179 , 327 , '2015-12-24' , 1 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (431 , 193 , 179 , 56 , '2015-12-26' , 3 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (432 , 192 , 180 , 302 , '2015-12-11' , 2 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (433 , 74 , 181 , 204 , '2015-12-09' , 0 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (434 , 115 , 181 , 415 , '2015-12-22' , 1 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (435 , 182 , 181 , 145 , '2016-01-06' , 3 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (436 , 82 , 182 , 25 , '2015-12-06' , 0 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (437 , 42 , 182 , 446 , '2015-12-11' , 0 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (438 , 9 , 183 , 198 , '2015-12-28' , 0 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (439 , 114 , 183 , 231 , '2015-12-06' , 0 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (440 , 78 , 184 , 213 , '2015-12-28' , 0 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (441 , 160 , 184 , 344 , '2015-12-07' , 1 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (442 , 97 , 185 , 367 , '2016-01-18' , 2 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (443 , 140 , 185 , 354 , '2016-01-23' , 1 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (444 , 41 , 186 , 115 , '2016-01-15' , 1 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (445 , 64 , 186 , 102 , '2016-01-06' , 0 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (446 , 65 , 186 , 344 , '2016-01-14' , 0 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (447 , 43 , 186 , 130 , '2016-01-17' , 0 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (448 , 159 , 186 , 160 , '2016-01-06' , 1 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (449 , 79 , 187 , 351 , '2016-01-11' , 1 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (450 , 166 , 187 , 162 , '2016-01-12' , 1 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (451 , 100 , 188 , 227 , '2016-01-27' , 4 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (452 , 35 , 188 , 344 , '2016-01-26' , 0 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (453 , 19 , 189 , 25 , '2016-02-08' , 0 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (454 , 32 , 189 , 414 , '2016-01-31' , 0 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (455 , 86 , 189 , 379 , '2016-02-01' , 0 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (456 , 108 , 189 , 182 , '2016-02-10' , 1 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (457 , 105 , 190 , 61 , '2016-02-11' , 2 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (458 , 209 , 190 , 340 , '2016-01-23' , 1 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (459 , 147 , 191 , 235 , '2016-02-16' , 2 )
INSERT INTO [dbo].[ConferenceDayReservation] (ReservationID, ParticipantsCount, ConferenceDayID, CustomerID, RegistrationDate, StudentsCount)
	 VALUES (460 , 167 , 191 , 238 , '2016-02-11' , 3 )
